-- 한밭대학교 장학금
-- supabase/scholarship_dedup_list.md 기준, 배치별로 아래에 이어서 추가함.
-- 참고용 데이터 백업 스크립트 — 새 DB에 재적재할 때 사용 (id는 SERIAL이라 자동 재할당됨)

-- 배치 1: 교내장학제도 (대학 전체 대상, 20건, id 134~153)
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('재학생 성적우수장학금', '한밭대학교', 'A급(평점평균 3.750 이상)은 등록금 전액, B급(3.500 이상)은 50%, C급(3.000 이상)은 30% 지원. 학과(부) 추천 필요, 직전학기 12학점 이상 취득자만 대상. 비교과교육과정 유닛 이수 기준 충족 필요(성인학습자 전담학과 제외).', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090101.do', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, 'semester', NULL, NULL, NULL, NULL, NULL, '직전학기 12학점 이상', NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('최우수장학금(신입생)', '한밭대학교', '정시 신규(수능성적 최상위)·수시 신규(전형총점 우수)는 입학학기 등록금 전액. 정시/수시 계속(2학기차 이상 유지)은 평점평균 3.750 이상 및 직전학기 12학점 이상 취득 시 등록금 전액 유지.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090102.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('신입생우수장학금', '한밭대학교', '입학 성적 등급에 따라 A급은 입학학기 등록금 전액, B급은 50%, C급은 30% 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090102.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '입학 성적 등급(A/B/C)에 따라 차등', NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('혜윰Ⅰ장학금', '한밭대학교', '국가장학금 수혜자 중 장학위원회 심의를 통해 선발, 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090103.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('혜윰Ⅱ장학금', '한밭대학교', '한국장학재단 학자금지원구간 8구간 이하 저소득층 중 평점평균 2.0 이상, 직전학기 12학점 이상 취득자 대상. 등록금 전액 또는 예산 범위 내 일부 지원(학생처장 승인).', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090103.do', NULL, NULL, NULL, NULL, NULL, 8, 2.0, 'semester', NULL, NULL, NULL, NULL, '직전학기 12학점 이상', NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('혜윰Ⅲ장학금', '한밭대학교', '아동복지법 제52조에 따른 아동양육시설·공동생활가정 생활자 또는 퇴소자 대상. 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090103.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('혜윰Ⅳ장학금', '한밭대학교', '재난·실직·폐업 등으로 1년 이내 가계곤란을 겪은 학생 중 학과장 추천 및 총장 인정자 대상(1회 지원). 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090103.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('새터민장학금', '한밭대학교', '북한이탈주민의 보호 및 정착지원에 관한 법률 제45·46조에서 정하는 교육지원대상자 대상. 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090104.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('보훈장학금', '한밭대학교', '국가유공자 등 예우 및 지원에 관한 법률 제22·25조에서 정하는 교육지원대상자 대상. 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090104.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('학석사통합과정 장학금', '한밭대학교', '2018학년도 이후 입학한 신입생 중 석사과정 진학을 결정한 학생 대상. 입학학기 등록금 20%, 석사과정 진학 직전학기 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('국외교류장학금', '한밭대학교', '국외교류 또는 복수학위 프로그램 선정 학생 대상. 교류 학생은 본교 등록금 전액, 복수학위 학생은 50% 지원 + 자매대학 실납부금 50% 이내(최대 350만원) 추가 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'international_exchange'),
('학군제휴장학금', '한밭대학교', '교육부장관 추천 학생 대상. 등록금 30% 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('디딤돌장학금', '한밭대학교', 'A등급(1~3급)은 등록금 전액, B등급(4~6급)은 등록금 50% 지원. 등급 산정 기준은 장학위원회 심의로 결정.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('다문화가정장학금', '한밭대학교', '다문화가족 구성원 중 직전학기 평점평균 3.0 이상, 12학점 이상 취득자 대상. 등록금 50% 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, 'semester', NULL, NULL, NULL, NULL, '직전학기 12학점 이상', NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('성취장학금', '한밭대학교', 'A등급은 등록금 전액, B등급은 등록금 50% 지원. 등급 산정 기준은 장학위원회 심의로 결정.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('학생활동 장학금(학생자치단체)', '한밭대학교', '총학생회·학회연합회·동아리연합회·신문방송국·학군사교육단 등 학생자치단체 임원 대상. 평점 기준 충족 시 등록금 전액 또는 50% 지원(학군사교육단은 직급별 30만원~150만원).', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('학술교류장학금(외국인)', '한밭대학교', '본교와 국외대학 간 체결된 학술교류협정에 따라 수학하는 외국인 학생 대상. 교환학생은 등록금 전액, 복수학위·공동학위는 협정에 따라 30~70% 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090106.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'international_exchange'),
('일반유학장학금(국립대학부외)', '한밭대학교', '국제학부 외 학과 소속 외국인 유학생 대상. 신입생 A급(TOPIK 5급 이상)은 입학학기 등록금 전액, B급(TOPIK 4급)은 50%, C급(TOPIK 3급)은 30%. 재학생 A급(평점 3.700 이상)은 등록금 전액, B급(3.400~3.700)은 50%, C급(3.000~3.400)은 30%.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090106.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', NULL),
('일반유학장학금(국제학부)', '한밭대학교', '국제학부 소속 외국인 유학생 대상. 신입생 A급(IELTS 7.0 이상 등 우수 어학성적)은 입학학기 등록금 전액, B급(IELTS 6.0 이상)은 50%. 재학생은 평점 3.700 이상 전액, 3.400~3.700 50%, 3.000~3.400 30%.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090106.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', NULL),
('유학생성취장학금', '한밭대학교', '외국인 유학생 중 학업 성취가 우수한 학생 대상. 세부 선발 기준·지원금액은 장학위원회 심의로 결정 — 매 학기 초 공지 확인 필요.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090106.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', NULL);

-- 배치 8: 장학공지 게시판(외부재단·지자체) 재검증 중 확인된 신규분 (4건, 대학 무관 지역기반이라 eligible_university NULL, 2026-08-02)
-- 애초 배치7에서 "미확인(작성일 오래되고 소규모)"으로 스킵했던 5건 중 4건을 재검증해서 실존·2026년 진행중 확인 후 추가함(신화장학재단만 검색으로 못 찾아서 제외).
-- 울산 남구/익산시 2건은 eligible_region을 비워둠 — 시/도 전체가 아니라 그 안의 특정 구/시 단위로만 대상이 좁혀지는 장학금이라, 현재 시스템은 시/도 단위까지만 매칭 가능해서 그대로 eligible_region에 넣으면 다른 구/군 거주자한테도 잘못 매칭됨(과다매칭 방지 목적). 상세: matching_gaps.md 14번, CLAUDE.local.md 참고.
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('인천 청년 해외배낭연수 장학생', '인천인재평생교육진흥원', '2026-08-02 확인(공식 공고문 기준): 본인 또는 부모의 주소지가 1년 이상 인천에 등록된 만 19~34세 팀 단위 지원자 대상(팀 전원이 자격요건 충족 필요 — 개인 단위 조건이 아니라 완전히 구조화된 필드로 표현 불가). 해외배낭연수 경비(항공료·교통비·숙박비·현지활동비 등)를 팀당 최대 1,000만원 범위 내 국가별 차등 지원. 1차 서류심사(3배수)→2차 제안서 평가(PT)로 5개 팀 선발. 매년 재공고되는 사업(2026년도분 공고 확인).', NULL, 'https://itle.or.kr', 19, 34, NULL, '인천', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5개 팀', '매년 재공고 (2026년도분 진행중, 정확한 마감일은 공고문 확인 필요)', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'local_gov'),
('전북 향토인재 장학생', '전북특별자치도평생교육장학진흥원', '2026-08-02 확인(공식 공고문 기준): 전북 출신(연고) 대학생 중 학업성적 우수자 또는 가정형편이 어려운 학생 대상. 200명 선발(서울 소재 4년제 50명, 지방대·전문대 150명). 1인당 100만원(생활비 지원). 2026년도분 신청기간 2026.4.6~4.12(이미 마감) — 매년 4월경 재공고되는 정기 사업.', 1000000, 'https://www.jbiles.or.kr', NULL, NULL, NULL, '전북', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '200명', '매년 4월경 재공고 (2026년도분은 2026.4.6~4.12 마감)', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'local_gov'),
('우듬지인재키움 장학사업(울산 남구)', '울산남구장학재단', '2026-08-02 확인(뉴스·재단 홈페이지 기준): 울산 남구에 1년 이상 주민등록된 자 대상(중·고생은 남구 소재 학교 재학생, 대학생은 남구 내 학교 중 1곳 이상 졸업한 경우). 중학교부터 대학 졸업까지 최대 12년간 재능계발비 지원 — 대학생 기준 연 400만원(중학생 200만원/고등학생 300만원). 1차 서류심사+2차 면접, 2025년 첫 시행으로 15명 선발된 신설 사업. eligible_region은 "울산 남구"로 시/군/구 단위까지 한정되는데 현재 시스템은 시/도 단위까지만 매칭 가능해 비워둠(matching_gaps.md 14번 참고) — 남구 거주 여부는 이 설명 텍스트로만 확인 가능.', 4000000, 'https://www.unsf.or.kr', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '15명(2025년 기준, 매년 변동 가능)', '매년 재공고 (2025년 첫 시행, 2026년 진행 여부는 재단 홈페이지 확인 필요)', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'local_gov'),
('대학생 학자금 대출이자 지원(익산시)', '익산시', '2026-08-02 확인(공식 공고문 기준): 익산시에 거주하는 대학(원)생 또는 졸업 5년 이내자 대상. 2017년 이후 한국장학재단 학자금대출(등록금·생활비)의 이자를 지원, 연 2회(상·하반기) 신청. 2026년 상반기분은 2026.3.16~4.3 신청 마감. eligible_region은 "익산시"로 시/군 단위까지 한정되는데 현재 시스템은 시/도 단위까지만 매칭 가능해 비워둠(matching_gaps.md 14번 참고) — 익산시 거주 여부는 이 설명 텍스트로만 확인 가능. 군산시 등 인접 도시에 유사 제도가 있는지는 검색으로 확인 못함.', NULL, 'http://www.iksan.go.kr', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '연 2회(상/하반기), 2026년 상반기분 2026.3.16~4.3 마감', NULL, NULL, NULL, NULL, NULL, NULL, 'support_fund', 'youth_living_support');
