-- 대전대학교 장학금
-- supabase/scholarship_dedup_list.md 기준, 새로 발견한 배치를 아래에 정리함.
-- id는 SERIAL이라 실제 DB에 넣을 때 자동 재할당됨 (여기서는 id 값 지정 안 함).
--
-- 출처: 대전대학교 학사지원실 > 학사안내 > 장학제도 "장학금 종류 및 지급기준"
--   (https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064)
--   이 페이지 하나가 신입생/재학생 교내장학금 전체(표 형태, 지급대상·선발기준·지급액 포함)를
--   정리해둔 중앙 페이지라, 학과별 게시판을 반복 확인할 필요가 크게 없었음(자세한 내용은
--   dju_progress.md 참고). 아래 school_internal 항목은 모두 이 페이지가 출처.
--
-- GPA 환산: 2026-08-02 공식 학칙시행세칙 제36조로 확인 완료 — 4.5만점제, 구간제(A+ 4.00~4.50/
-- A0 3.50~4.00/B+ 3.00~3.50/B0 2.50~3.00/C+ 2.00~2.50/C0 1.50~2.00/D+ 1.00~1.50/
-- D0 0.50~1.00/F 0.50 미만). 대전권 다른 대학 다수(충남대·한밭대·배재대·목원대·우송대·한남대)와
-- 동일한 4.5만점제로 확인됨. 아래 min_gpa 값은 전부 "평점평균"이라고 명시된 항목만 채웠고
-- (백분위/실점 점수는 GPA가 아니라서 min_gpa에 넣지 않고 description에 텍스트로만 남김),
-- 4.5만점제 기준 그대로의 값임 — 재수정 불필요.

-- 배치 1: 교내장학금 - 신입생 (6건)
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('특별장학금(신입생)', '대전대학교', '한의예과·군사학과 제외. 공통기준: 수능 영어영역 2등급 이내, 탐구영역(직업탐구 제외) 2과목 평균 반영. 일반학과(부)는 국어·수학·탐구영역 중 2개 영역 백분위 합 160점 이상, 간호학과·물리치료학과는 국어·수학·탐구영역 백분위 합 240점 이상. 등록금 전액, 이후 매학기 직전학기 15학점 이상 취득·평점평균 3.5 이상 유지 시 4년간 지급(수시/정시 공통).', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 3.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, '수능 영어 2등급 이내, 국어·수학·탐구 백분위 합 160점(일반학과)/240점(간호·물리치료학과) 이상', NULL, '입학 시 전형 결과로 자동 선발 (수시/정시 모집요강 참고)', '대전대학교', NULL, 'undergrad_enrolled', 1, 1, NULL, 'school_internal', 'academic_merit'),
('군사학과여학생특별장학금', '대전대학교', '군사학과 여자 신입생 대상. 수능 국어·수학·영어 평균 2등급 이내는 등록금 전액(이후 직전학기 15학점+평점평균 4.0 이상 유지 시 4년), 평균 3등급 이내는 수업료 일부(직전학기 15학점+평점평균 3.5 이상 유지)(수시/정시 공통).', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, 'female', NULL, NULL, NULL, 3.5, 'semester', NULL, NULL, NULL, '군사학과', NULL, NULL, '수능 국어·수학·영어 평균 2등급 이내(전액) 또는 3등급 이내(일부)', NULL, '입학 시 전형 결과로 자동 선발 (수시/정시 모집요강 참고)', '대전대학교', NULL, 'undergrad_enrolled', 1, 1, NULL, 'school_internal', 'academic_merit'),
('신입생 전형별 수석·차석 장학금', '대전대학교', '교과면접전형·교과중점전형·지역인재Ⅰ·Ⅱ전형(통합선발)·혜화인재전형·고른기회전형·농어촌학생전형·특성화고교졸업자전형·기회균형전형·군사학과전형 등 각 전형별로 모집단위(학과) 또는 단과대학별 수석·차석을 선발해 수업료 일부 지급(한의예과는 인문/자연 통합 1명). 실기위주전형(커뮤니케이션디자인학과·영상애니메이션학과·공연예술콘텐츠학과·생활체육학과·건강운동관리학과)도 모집단위별 수석을 별도 선발. 이후 직전학기 15학점 이상 취득·평점평균 3.5 이상 유지 시 1년간 지급. 전형 종류가 매칭 가능한 필드로 표현되지 않아 하나로 통합 기재함.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 3.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '입학 시 전형 결과로 자동 선발 (수시/정시 모집요강 참고)', '대전대학교', NULL, 'undergrad_enrolled', 1, 1, NULL, 'school_internal', 'academic_merit'),
('체육특기자장학금(신입생)', '대전대학교', '검도·펜싱·정구·복싱 특기자 대상(수시). 등록금 전액, 1년 지급.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '입학 시 전형 결과로 자동 선발 (수시 모집요강 참고)', '대전대학교', NULL, 'undergrad_enrolled', 1, 1, NULL, 'school_internal', 'activity_merit'),
('전체수석장학금(정시)', '대전대학교', '정시 전체수석 합격자 대상. 등록금 전액, 이후 직전학기 15학점 이상 취득·평점평균 3.5 이상 유지 시 졸업 시까지 지급.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 3.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '입학 시 전형 결과로 자동 선발 (정시 모집요강 참고)', '대전대학교', NULL, 'undergrad_enrolled', 1, 1, NULL, 'school_internal', 'academic_merit'),
('단대수석장학금(정시)', '대전대학교', '정시 단과대학별 수석 합격자 대상. 등록금 전액, 이후 직전학기 15학점 이상 취득·평점평균 3.5 이상 유지 시 일반학과 3년/한의예과 4년간 지급.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 3.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '입학 시 전형 결과로 자동 선발 (정시 모집요강 참고)', '대전대학교', NULL, 'undergrad_enrolled', 1, 1, NULL, 'school_internal', 'academic_merit');

-- 배치 2: 교내장학금 - 재학생 (33건)
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('성적우수장학금(대전대)', '대전대학교', '학과·학년별 재학인원 대비 성적순으로 5단계 차등 지급: 최우수성적(등록금100%), 성적우수A(70%), 성적우수B(50%), 성적우수C(30%), 성적우수D(15%). 공통 최소기준은 직전학기 15학점 이상 취득(최종학년 10학점)·평점평균 3.0 이상(F·N·미이수 과목 있으면 제외). 매학기 지급.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, 'semester', NULL, NULL, NULL, NULL, NULL, '직전학기 15학점 이상(최종학년 10학점)', NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('복지장학금(대전대)', '대전대학교', '국가장학금 1~8분위 대상자 중 직전학기 12학점 이상 취득·백분위점수 80점 이상인 자. 소득분위별 차등 지급, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '직전학기 12학점 이상', NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('마중물장학금', '대전대학교', '국가장학금 0분위(기초생활수급자) 대상자 중 직전학기 12학점 이상 취득·백분위점수 80점 이상인 자. 등록금의 20%, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '직전학기 12학점 이상', NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('장학사정관장학금', '대전대학교', '장학사정관 심사로 차등 지급(등록금 일부, 매학기). 대상: 다자녀(3자녀 이상), 중증질병 및 상해(1년 이상 연속 의료비 정산서), 실직가정·재난 및 재해(주민센터 확인서), 긴급가계곤란자(부도·파산 관계서류), 희망장학금(부모 중 장애등급 1~3급), 다문화가정자녀(부모 중 한 사람이 외국인, 귀화자·결혼이민자 포함), 기타 경제적 어려움 소명자 — 여러 특수상황 조건이 하나의 장학금에 OR로 묶여있어 구조화된 필드 하나로 표현 불가(matching_gaps.md 9번·12번 참고).', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('희망도전장학금', '대전대학교', '당해학기 국가장학금 신청자 중 성적기준 미달로 수혜받지 못한 자(직전학기 백분위점수 80점 미만). 등록금 일부, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('교직원자녀장학금(대전대)', '대전대학교', '전임교원·정규직원의 직계자녀 대상. 직전학기 15학점 이상 취득(최종학년 10학점)·평점평균 3.0 이상(유급제도 시행학과는 2.5 이상) 필요. 등록금의 50%, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, 'semester', NULL, NULL, NULL, NULL, NULL, '직전학기 15학점 이상(최종학년 10학점)', NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('재단직원자녀장학금', '대전대학교', '법인 임직원, 부속병원 및 혜화병원 정규직원, 학교설립유공자의 직계자녀 대상. 등록금의 50%, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('열정장학금', '대전대학교', '장애지원센터에 등록된 장애학생 대상(직전학기 실점평균 70점 이상). 중증장애 100만원 / 경증장애 30만원, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('동문자녀장학금(대전대)', '대전대학교', '본교 재학생 중 부모 1인이 본교 졸업생인 경우. 학기당 30만원.', 300000, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('보훈장학금(대전대)', '대전대학교', '보훈청의 대학수업료 등 면제대상증명서를 발급받은 국가유공자 본인 및 그 자녀 대상(본인은 성적 제한 없음, 자녀는 직전학기 백분위점수 70점 이상). 등록금 전액, 매학기. 국가보훈처/한국장학재단을 통한 교외 나라사랑장학금과는 별개의 대전대학교 자체 교내 장학금.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('새터민장학금(대전대)', '대전대학교', '국내 고등학교 졸업 또는 고졸 이상 학력 인정일로부터 5년 이내에 입학·편입학한 북한이탈주민 본인 및 그 자녀 대상(본인은 2회 연속 70점 미만이면 제한, 자녀는 직전학기 백분위점수 70점 이상). 등록금 전액, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('고시장학금(대전대)', '대전대학교', '국가고시(5급 이상) 및 이에 준하는 고시 1차·2차·최종 합격자 대상(직전학기 15학점 이상 취득(최종학년 10학점)·평점평균 3.0 이상). 1차합격자 등록금의 50%, 2차합격자·최종합격자는 등록금 전액. 수시 지급.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, 'semester', NULL, NULL, NULL, NULL, NULL, '직전학기 15학점 이상(최종학년 10학점)', NULL, NULL, '수시 (합격 발표 후 신청, 대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('가족장학금(대전대)', '대전대학교', '직계가족 2인 이상이 본교 재학 중인 경우, 직전학기 성적 백분위점수 70점 이상인 재학생 각자에게 학기당 50만원 지급.', 500000, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('외국인장학금(대전대)', '대전대학교', '토플·IELTS·토픽(TOPIK)이 일정 성적 이상인 외국인 재학생 대상. 성적별 차등 지급(등록금 일부), 매학기. 시험 종류·점수 조건이라 현재 시스템 필드로는 세부 매칭 불가(matching_gaps.md 10번 참고).', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'international_exchange'),
('계절학기장학금(대전대)', '대전대학교', '현장실습교과목, 유연학기제에 따른 집중이수제, DJU나노디그리 교과목, 공유대학 교과목, 산업체요구형 캡스톤디자인 이수자 대상. 수업료 전액, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('편입생장학금(대전대)', '대전대학교', '편입학 등록자 전원 대상. 본교 졸업자는 수업료의 70%, 그 외 편입학 등록자는 수업료의 50%. 첫학기 지급.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '첫 학기 등록 시 자동 지급 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_transfer', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('자기추천장학금(대전대)', '대전대학교', '자기주도적 특별한 경험을 통해 1년간 비전을 설계·실행하는 자로서 5학기 이상 등록한 자(직전학기 교내외 장학금 수혜내역 없거나 일정금액 미만, 직전학기 평점평균 3.0 이상, 15학점 이상 이수, 재학중 1회 수혜). 등록금 일부, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, 'semester', NULL, NULL, NULL, NULL, NULL, '직전학기 15학점 이상', NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', 3, NULL, NULL, 'school_internal', 'activity_merit'),
('총장특별장학금(대전대)', '대전대학교', '대외적으로 대전대학교의 위상을 드높인 자 또는 장학금 지급이 필요하다고 총장이 인정·승인한 자 대상. 제한 없음, 등록금 일부, 수시 지급(총장 재량 심사 성격이라 구체적 자격조건 없음).', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('체육특기자장학금(재학생, 대전대)', '대전대학교', '각종 대회에서 우수한 성적을 거둔 체육특기자 대상. 등록금 전액, 매학기. 같은 계열로 전지훈련 참가자에게 등록금 일부를 수시 지급하는 "전지훈련장학금"도 있음.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('전지훈련장학금', '대전대학교', '체육특기자 중 전지훈련에 참가하는 자 대상. 등록금 일부, 수시 지급.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('학과장학금(대전대)', '대전대학교', '전체 학과 대상. 교내·외 공모전 입상자나 학과 홍보 및 전공 특성화에 기여한 자에게 등록금 일부를 수시 지급.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('군사학과장학금(재학생)', '대전대학교', '군사학과 재학생 대상: 여학생 생활관지원비, 잠재역량(텝스·졸업인증), 학과특성화, 해외연수 참여자에게 등록금 일부를 수시 지급.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '군사학과', NULL, NULL, NULL, NULL, '수시 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('계약학과장학금', '대전대학교', '계약학과 재학생 대상. 등록금의 15%, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('외국어특별장학금(대전대)', '대전대학교', '외국어 관련 3개 세부 프로그램 이수/성적 우수자에게 등록금 일부를 수시 지급: 정기토익(본교 개최 정기토익 2회 이상 응시, 500점 이상 취득자), 토익캠프(토익캠프 수료자), 외국어역량강화(어학 관련 프로그램 이수자).', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('취업역량 장학금(대전대)', '대전대학교', '취업 관련 5개 세부 프로그램 참여/수료자에게 등록금 일부를 수시 지급: 재학생직무체험(직무연수 수료자), 글로벌인재육성(4학년2학기 재학중 해외취업알선사업 참가자 또는 해외취업 근로계약 체결자), 취업동아리(엘리트코칭·취창업지원팀 주관 취업동아리 참가자), 취업리포터즈(취업리포터즈 선발·활동자), 취업역량제고(관련 교육과정 수료자).', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('봉사공로 장학금(대전대)', '대전대학교', '봉사·공로 관련 9개 세부 항목에 등록금 일부를 지급(대부분 수시, 학생회임원봉사는 매학기): 학생회임원봉사(총학생회·단과대학학생회 임원, 동아리연합회 임원, 전학대 의장, 학회장), 국외봉사(국외봉사 참가자 중 모범자), 외국인봉사(통역의전요원·유학생봉사요원·유학생임원·버디), 봉사(각종 행사 및 교내외 부서 업무 참여자), 행사공로(대동제·비전위크·길거리·벚꽃나들이 등 행사 참여자), HRC(HRC 튜터·프로그램 참여자), 푸른별홍보대사, 입시홍보(학교투어·고교초청행사 지원, 출신고교 대상 입시홍보자), 학군단(모범후보생·학군여학우집체장학금·입영훈련우수자·문화탐방참여자·리더십·자치근무자).', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시/매학기 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('성적향상장학금(대전대)', '대전대학교', '최근 2개 학기 성적을 비교해 큰 폭으로 향상된 학생 대상(평점평균이 1.1~2.0 이상 향상한 경우). 절대 성적이 아닌 향상폭 기준이라 min_gpa로 표현 불가. 등록금 일부, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('교환학생장학금(대전대)', '대전대학교', '파견희망국 공인어학능력 성적 소지자 중 교환학생으로 선발된 2~3학년 재학생 대상(전체학기 평균 평점 3.0 이상). 등록금 일부, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, 'cumulative', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', 2, 3, NULL, 'school_internal', 'international_exchange'),
('글로벌인사이트장학금', '대전대학교', '하계·동계 단기해외연수 프로그램 이수자, 단기해외연수 결과보고대회 발표우수팀 대상(전체학기 평균 평점 3.0 이상). 등록금 일부, 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, 'cumulative', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'international_exchange'),
('마일리지장학금(대전대)', '대전대학교', '6개 영역(학업/봉사/취업 등)에 마일리지를 부여해 누적점수가 500점 이상일 경우 장학금으로 전환(직전학기 15학점 이상 신청, 평점평균 2.0 이상). 등록금 일부, 한 학기 지급.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 2.0, 'semester', NULL, NULL, NULL, NULL, NULL, '직전학기 15학점 이상', NULL, NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('기타 역량강화·마일리지 장학금(대전대)', '대전대학교', '역량강화 관련 6개 세부 항목에 등록금 일부를 지급(대부분 수시/매학기): 아너스장학금(프로그램 참가 적극성 및 교육성과 우수자, 평가 후 차등지급), 공모전및경시대회(교내 각종 공모전·경시대회 우수자), 도서관마일리지(도서포인트70%+좌석이용포인트30% 누적자), 독서인증(도서관 추천도서 읽고 시험 패스한 자), 학생역량강화장학금(비전탐색·비전설계·DUIMS·블로그기자단·ASEAN포럼·스포츠건강체력·학생홍보단·현장실습 등 프로그램 참여자, 한학기), 기금인출장학(발전기금·장학기금으로 적립된 장학금, 해당부서 요청에 의해 지급).', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시/매학기 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('융합인재장학금(대전대)', '대전대학교', '융·복합 전공교육과정 이수학생 대상. 해당학기 평점평균 3.5 이상, 동일학기 융복합전공 교과목(제1전공 포함) 6학점 이상 이수자 중 성적순 선발. 6학점 이상 10만원 / 9학점 이상 20만원(총 70명 이내), 매학기.', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, 3.5, 'semester', NULL, NULL, NULL, NULL, NULL, '동일학기 융복합전공 교과목 6학점 이상', '총 70명 이내', NULL, '매 학기 초 공지 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('디딤돌장학금(대전대)', '대전대학교', '비교과 프로그램 참가에 포인트를 부여해 누적 포인트가 있는 자를 선발. 등록금 일부, 연 1회 지급. 학교 자체 비교과 이수 조건이라 별도 매칭 필드 없이 텍스트로만 기록(matching_gaps.md 11번 방침).', NULL, 'https://www.dju.ac.kr/dju/cm/cntnts/cntntsView.do?mi=1172&cntntsId=1064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '연 1회 (대전대학교 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit');

-- 배치 3: 대전대학교 RISE사업단 자체 프로그램 (1건)
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('창업마일리지 장학금', '대전대학교 RISE사업단', '창업교과/비교과 마일리지를 취득한 재학생 대상. 창업 마일리지 신청서, 창업활동 수기, 외부 프로그램 참여 증빙자료(상장·수료증), 롤모델 창업특강 수료증 제출 필요. 매년 약 2천만원 규모를 마일리지 취득 학생들에게 지급(연례 프로그램, 2025학년도 기준 신청마감 1.19).', NULL, 'https://www.dju.ac.kr/djurise/main.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매년 1월경 모집 (정확한 시기는 RISE사업단 홈페이지 확인)', '대전대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit');

-- 배치 4: 대학 무관 신규 발견 국가/지자체·재단 장학금 (5건, eligible_university NULL)
-- 대전대학교 장학공지 게시판(https://www.dju.ac.kr/dju/na/ntt/selectNttList.do?bbsId=1853&mi=3957)에서 발견.
-- 이 5건은 대전대에서 발견했지만 대학 무관 전국/재단 공통 프로그램이라 eligible_university를 비워둠.
-- **주의(다른 병렬 크롤링과 중복 가능성)**: 을지대학교/침례신학대학교를 동시에 크롤링 중인
-- 다른 에이전트가 같은 이름을 독립적으로 발견했을 가능성이 있음 — 병합 시 각별히 대조 필요.
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('대한민국 인재상', '한국장학재단(교육부)', '대한민국 국적의 만 15~34세 청년 중 탁월한 성취·창의적 사고·사회기여 등 기준에 부합하는 인재 100명 선발(대학 소속 무관, 개인 자격 신청 가능). 국무총리상 1명(상장+300만원), 교육부장관상 99명(상장+200만원). 접수 2026.7.14~8.19 18:00, 한국장학재단 누리집 신청+추천서 시도청 우편제출.', 2000000, 'https://www.dju.ac.kr/dju/na/ntt/selectNttList.do?bbsId=1853&mi=3957', 15, 34, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '100명', '2026.7.14~2026.8.19 18:00', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('농업인자녀장학금', '한국농어촌희망재단', '농업인 자녀 중 신청자 대상(학과·전공 제한 없음, 국가장학금 0~8분위만 신청 가능). 재학중 직전학기 백분위점수 80점 이상·취득학점 12학점 이상(농어촌희망재단 지급계획에 따라 변동 가능). 등록금 일부, 매학기.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '직전학기 12학점 이상', NULL, NULL, '매학기 (한국농어촌희망재단 공고 확인)', NULL, NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'private_foundation'),
('의용소방대자녀장학금', '의용소방대', '의용소방대에서 선발된 자(의용소방대원 본인 또는 자녀) 대상. 의용소방대 자체 기준에 준해 등록금 일부 지급, 매학기.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매학기 (소속 의용소방대 확인)', NULL, NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'local_gov'),
('새마을지도자자녀장학금', '새마을운동중앙회', '새마을지도자 자녀로 선발된 자 대상. 새마을회 자체 기준에 준해 등록금 일부 지급, 매학기.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매학기 (소속 새마을회 확인)', NULL, NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'local_gov'),
('서울희망장학금', '(재)서울장학재단', '(재)서울장학재단의 선발 및 추천을 받은 서울 거주 대학생 대상(비서울 소재 대학 재학생 포함). 서울장학재단 자체 기준에 따라 등록금 일부 지급, 매학기.', NULL, NULL, NULL, NULL, NULL, '서울', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매학기 ((재)서울장학재단 공고 확인)', NULL, NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'local_gov');
