-- 한밭대학교 장학금
-- supabase/scholarship_dedup_list.md 기준, 배치별로 아래에 이어서 추가함.
-- 참고용 데이터 백업 스크립트 — 새 DB에 재적재할 때 사용 (id는 SERIAL이라 자동 재할당됨)

-- 배치 1: 교내장학제도 (대학 전체 대상, 20건, id 134~153)
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('재학생 성적우수장학금', '한밭대학교', 'A급(평점평균 3.750 이상)은 등록금 전액, B급(3.500 이상)은 50%, C급(3.000 이상)은 30% 지원. 학과(부) 추천 필요, 직전학기 12학점 이상 취득자만 대상. 비교과교육과정 유닛 이수 기준 충족 필요(성인학습자 전담학과 제외).', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090101.do', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, NULL, NULL, NULL, NULL, NULL, '직전학기 12학점 이상', NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('최우수장학금(신입생)', '한밭대학교', '정시 신규(수능성적 최상위)·수시 신규(전형총점 우수)는 입학학기 등록금 전액. 정시/수시 계속(2학기차 이상 유지)은 평점평균 3.750 이상 및 직전학기 12학점 이상 취득 시 등록금 전액 유지.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090102.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('신입생우수장학금', '한밭대학교', '입학 성적 등급에 따라 A급은 입학학기 등록금 전액, B급은 50%, C급은 30% 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090102.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '입학 성적 등급(A/B/C)에 따라 차등', NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('혜윰Ⅰ장학금', '한밭대학교', '국가장학금 수혜자 중 장학위원회 심의를 통해 선발, 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090103.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('혜윰Ⅱ장학금', '한밭대학교', '한국장학재단 학자금지원구간 8구간 이하 저소득층 중 평점평균 2.0 이상, 직전학기 12학점 이상 취득자 대상. 등록금 전액 또는 예산 범위 내 일부 지원(학생처장 승인).', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090103.do', NULL, NULL, NULL, NULL, NULL, 8, 2.0, NULL, NULL, NULL, NULL, '직전학기 12학점 이상', NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('혜윰Ⅲ장학금', '한밭대학교', '아동복지법 제52조에 따른 아동양육시설·공동생활가정 생활자 또는 퇴소자 대상. 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090103.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('혜윰Ⅳ장학금', '한밭대학교', '재난·실직·폐업 등으로 1년 이내 가계곤란을 겪은 학생 중 학과장 추천 및 총장 인정자 대상(1회 지원). 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090103.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('새터민장학금', '한밭대학교', '북한이탈주민의 보호 및 정착지원에 관한 법률 제45·46조에서 정하는 교육지원대상자 대상. 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090104.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('보훈장학금', '한밭대학교', '국가유공자 등 예우 및 지원에 관한 법률 제22·25조에서 정하는 교육지원대상자 대상. 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090104.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('학석사통합과정 장학금', '한밭대학교', '2018학년도 이후 입학한 신입생 중 석사과정 진학을 결정한 학생 대상. 입학학기 등록금 20%, 석사과정 진학 직전학기 등록금 전액 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('국외교류장학금', '한밭대학교', '국외교류 또는 복수학위 프로그램 선정 학생 대상. 교류 학생은 본교 등록금 전액, 복수학위 학생은 50% 지원 + 자매대학 실납부금 50% 이내(최대 350만원) 추가 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'international_exchange'),
('학군제휴장학금', '한밭대학교', '교육부장관 추천 학생 대상. 등록금 30% 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('디딤돌장학금', '한밭대학교', 'A등급(1~3급)은 등록금 전액, B등급(4~6급)은 등록금 50% 지원. 등급 산정 기준은 장학위원회 심의로 결정.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('다문화가정장학금', '한밭대학교', '다문화가족 구성원 중 직전학기 평점평균 3.0 이상, 12학점 이상 취득자 대상. 등록금 50% 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, NULL, NULL, NULL, NULL, '직전학기 12학점 이상', NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('성취장학금', '한밭대학교', 'A등급은 등록금 전액, B등급은 등록금 50% 지원. 등급 산정 기준은 장학위원회 심의로 결정.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('학생활동 장학금(학생자치단체)', '한밭대학교', '총학생회·학회연합회·동아리연합회·신문방송국·학군사교육단 등 학생자치단체 임원 대상. 평점 기준 충족 시 등록금 전액 또는 50% 지원(학군사교육단은 직급별 30만원~150만원).', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090105.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('학술교류장학금(외국인)', '한밭대학교', '본교와 국외대학 간 체결된 학술교류협정에 따라 수학하는 외국인 학생 대상. 교환학생은 등록금 전액, 복수학위·공동학위는 협정에 따라 30~70% 지원.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090106.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'international_exchange'),
('일반유학장학금(국립대학부외)', '한밭대학교', '국제학부 외 학과 소속 외국인 유학생 대상. 신입생 A급(TOPIK 5급 이상)은 입학학기 등록금 전액, B급(TOPIK 4급)은 50%, C급(TOPIK 3급)은 30%. 재학생 A급(평점 3.700 이상)은 등록금 전액, B급(3.400~3.700)은 50%, C급(3.000~3.400)은 30%.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090106.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', NULL),
('일반유학장학금(국제학부)', '한밭대학교', '국제학부 소속 외국인 유학생 대상. 신입생 A급(IELTS 7.0 이상 등 우수 어학성적)은 입학학기 등록금 전액, B급(IELTS 6.0 이상)은 50%. 재학생은 평점 3.700 이상 전액, 3.400~3.700 50%, 3.000~3.400 30%.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090106.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', NULL),
('유학생성취장학금', '한밭대학교', '외국인 유학생 중 학업 성취가 우수한 학생 대상. 세부 선발 기준·지원금액은 장학위원회 심의로 결정 — 매 학기 초 공지 확인 필요.', NULL, 'https://www.hanbat.ac.kr/kor/sub05_090106.do', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (한밭대 홈페이지 확인)', '한밭대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', NULL);
