-- 충남대학교 장학금 — 하네스 자동 수집 초안 (2026-08-10)
-- 사람 리뷰 후 이 내용을 supabase/data_cnu.sql로 옮길 것.
-- 실제 DB 반영은 지금처럼 supabase/tools/run_sql.py를 사람이 직접 실행함 — 이 파일은 초안임.
-- needs_review로 플래그된 필드가 있는 행은 같은 이름의 harness_review_*.md에서 근거를 먼저 확인할 것.

INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, required_disability_type, foreigner_eligibility, language_test_type, language_test_min_score, required_special_status, application_deadline, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('백마드림(Ⅰ·Ⅱ) 장학금', '충남대학교발전기금재단', '충남대학교발전기금재단 재원으로 다양한 학문분야의 우수학생을 육성하기 위해 등록금 외로 지원하는 장학금. 백마드림Ⅰ은 학업장려비 학기당 500만원(계속지원기준 유지 시 8개 학기 지원), 모집단위별 1명 이내. 백마드림Ⅱ는 학업장려비 학기당 300만원(계속지원기준 유지 시 2개 학기 지원), 모집단위별 2명 이내. 모집시기별(수시/정시), 계열별(인문계/자연계), 모집단위별 수능성적 우수자 대상. 기준 성적 2회 이상 미달 또는 징계 등으로 장학생 선발이 부적절하다고 인정될 경우 장학생 자격 박탈. 1학년(2개 학기) 수료 이전 자퇴 시 장학금 전액 환수. 장학금액은 매 학기 종료후 지급(1학기는 8월까지, 2학기는 2월까지). 충남대학교 발전기금재단 장학생으로서 재단에서 행사 참여 등의 요청 시 특별한 사정이 있는 경우를 제외하고는 적극적으로 참여하여야 함.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3.75, 'semester', NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, '15학점', '모집시기별(수시/정시), 계열별(인문계/자연계), 모집단위별 수능성적 우수자', '백마드림Ⅰ: 모집단위별 1명 이내, 백마드림Ⅱ: 모집단위별 2명 이내', NULL, '충남대학교', NULL, 'undergrad_enrolled', 1, 1, NULL, 'school_internal', 'academic_merit'),
('CNU Honor Scholarship 장학금', '충남대학교', '본교 학사 및 석·박사 전과정 등록금 전액, 학업장려금 연 1천 5백만원, 학생생활관 우선 배정 및 생활관비 면제, 글로벌 파견 프로그램(CNU GHS) 우선 선발, 석·박사 해외유학 장려금 1억원(석사과정 4천만원, 박사과정 6천만원) 지원. 계속지원기준 2회 미달 시 자격 박탈, 학부 1학년(2개 학기) 수료 이전 자퇴 시 지원 중단 및 학업장려금 전액 환수. 대학원 장학지원은 학부 또는 석사 졸업 후 1년 이내 입학하는 경우에 한함. 글로벌엘리트 및 백마드림 장학금과 중복수혜 불가. 2021학년도 신입생부터 적용.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3.75, 'semester', NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, '의예과, 수의예과, 약학과는 제외', '직전학기 15학점 이상 이수 (대학원은 이수학점기준 없음)', '수능 전 영역(국어, 영어, 수학, 탐구) 1등급인 자', NULL, NULL, '충남대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('2012년도 국가장학금 및 교내장학금', '충남대학교', '교과부에서는 대학 등록금 인하와 관련하여 국가장학금을 대폭 확대(1조5천억원)하여 대부분의 학생들에게 장학금을 지급할 예정으로 반드시 학생 본인이 신청하여야 혜택을 받을 수 있고 이와 연계하여 교내 장학금도 지급할 예정임. 국가장학금은 등록금 범위내(연간최대 450만원)에서 예산 및 소득분위에 따라 지급되며, 교내장학금(복지)은 국가장학금 지급대상자로 선정된 학생을 대상으로 개인별 소득분위에 따라 등록금 범위 내에서 차등 지급됨.', NULL, 'http://www.kosaf.go.kr', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '2011-12-30', NULL, NULL, NULL, NULL, NULL, NULL, '''11. 12. 5(월) ~ 12. 30(금)', '충남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2011년 2학기 백마(복지)장학생 (가계곤란자)', '충남대학교', '백마(복지) 장학금(신설)으로 가계곤란자를 대상으로 하며, 저소득층 장학금 지원자 인원 등을 고려하여 장학예산 범위 내에서 장학금액이 결정되며 한국장학재단 국가장학생 중복 선발 시 국가장학생 우선 선발. 한국장학재단 차상위계층 지원(국가 희망드림) 사업 계속 확정 시 해당 기준에 해당하는 학생은 국가 장학금을 신청하여야 함(신청 시 등록금 차액은 지원함). 선발 우선순위: 1순위 기초생활수급자·차상위계층자, 2순위 소득하위 50% 이하 가구 학부생, 3순위 학과장 또는 지도교수 추천 일시적 가계곤란자(긴급재난, 불의의 사고, 실직, 기타가계곤란), 4순위 3자녀이상 다자녀 가구 또는 다문화 가정 자녀, 5순위 직전학기 성적 우수자, 6순위 직전학기 취득 학점이 많은 자, 7순위 전체학기 평균평점이 높은 자.', 750000, NULL, NULL, NULL, NULL, NULL, NULL, 50, 2.6, 'semester', FALSE, NULL, NULL, NULL, NULL, ARRAY['basic_livelihood_recipient','near_poor','job_loss_or_disaster','financial_emergency','multi_child_family','multicultural_family'], NULL, NULL, NULL, NULL, '직전학기 12학점 이상 이수', NULL, '1,300명', NULL, '충남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'welfare_living'),
(NULL, '충남대학교', '2011년도 제2학기 교내장학생 선발 관련 주요 변경사항 공지. 우수장학생 선발비율, 외국어우수장학생(삭제), 대학원 외국인장학생 감면율, 저소득층 장학금(백마C/백마D/백마(복지)장학금), 교육역량강화사업 장학금(경력개발우수장학금, 학장추천장학금, 성적우수장학금 등) 관련 변경 전/후 내용을 비교 안내함.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, '백마(복지) 장학금: 직전학기 12학점 이상, 백마C/백마D: 15학점 이상(졸업학기 및 교류자는 12학점)', NULL, NULL, NULL, '충남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', NULL),
('2011년도 교육역량강화사업 장학생', '충남대학교', '교육역량강화장학금은 경력개발 우수장학금(경력개발 프로그램 참여 실적 우수자 선발), 학장 추천 장학금(학업성적 향상자, 어학능력 향상자, 가계곤란자 등), 성적우수 장학금(성적우수자 장학금 지원)으로 구성됨. 경력개발우수장학금은 2012.1월 중 신청 및 지급 예정, 학장추천 장학금은 소속학과 사무실로 제출, 성적우수장학금은 별도 신청 없이 교내 성적장학금 선정과 같은 방법으로 학과에서 선정.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '2011-07-27', NULL, NULL, NULL, NULL, NULL, '총 1,771명 (경력개발 우수장학금 676명, 학장 추천 장학금 700명, 성적우수 장학금 395명)', NULL, '충남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('2010년 대학교육역량강화사업 장학금', '충남대학교', '2010년 대학교육역량강화사업 장학금 지원 안내. 1. 성적우수(교육역량강화) : 선발 완료됨(2010.8.9) 2. 교육역량우수자 장학금 : 개인별 마일리지 누적실적에 따라 2011.2월말 선발 예정 3. 백마(교육역량강화) : 경제사정 곤란자 장학금으로서 2010.8.9 이후 신청대상자는 본인 학과사무실로 문의바람', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['financial_emergency'], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '충남대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('2009 대학 교육역량강화사업 관련 장학금', '충남대학교', '우리대학에서 시행된 2009대학교육역량강화사업 관련 장학금에 대해 알려드립니다.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '충남대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', NULL),
('2009년도 지역대학 우수학생 사업', '한국과학재단', '이공계열 학과(부) 재학 우수학생 대상 사업으로, 선발규모는 수능성적우수·입학성적우수·이공계열우수 등 1000여명이며, 입학금을 제외한 매학기별 등록금(수업료 및 기성회비)의 50%를 지원(계속지원기준 및 2+2제도 기준 충족시)하고, 기초생활수급자에게는 학기당 180만원의 생활비를 추가 지원함.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['basic_livelihood_recipient'], '2009-04-24', NULL, '이공계열 학과(부)', NULL, NULL, '수능성적우수, 입학성적우수 학생 선발', '1000여명', '2009.4.1(수)~4.24(금)까지(소속대학으로 증빙서 서류 필히 제출) [온라인신청 : 2009.4.1(수)14:00~2009.4.23(목)18:00시까지]', NULL, NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2009년도 이공계 국가장학생 사업', '한국과학재단', '수능성적우수 유형(기준1)으로 1,800여명 선발. 입학성적 유형은 4월 중, 재학중우수(2+2제도) 유형은 10월 중 별도 공지 예정. 계속지원기준 및 2+2제도기준 충족시 계속지원.', NULL, 'http://scholarship.kosef.re.kr', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['basic_livelihood_recipient'], '2009-03-26', NULL, '이공계', NULL, NULL, '수능성적우수 유형(기준1)', '1,800여명', '온라인 신청 기간 : 2009. 3. 5(목)~ 3.26(목)18:00까지', NULL, NULL, NULL, NULL, NULL, NULL, 'school_external', 'national_scholarship'),
(NULL, NULL, '2008 동계 캄보디아 해외봉사단 사진전 알림. 캄보디아 시엠립 봉사활동 사진전 개최 안내 (충남대학교 중앙도서관, 대전역, 제1후생관 등에서 순차 개최)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('09 1학기 미래로 장학금', '충남대학교', '수업연한 초과자도 장학금 수령 가능(단, 지원횟수 범위내 일 경우), 복수전공으로 인한 수업연한 초과자도 신청 가능', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '충남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
(NULL, '충남대학교', '충남대학교병원 진료비 감면 대상자 추가 확정 안내. 감면대상: 우리 대학교 기성회 상용계약직 및 기간제계약직. 감면시행일: 2008.12.30(화). 감면내용은 붙임 안내문 참조.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, '우리 대학교 기성회 상용계약직 및 기간제계약직', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('09 1학기 미래로 장학금', '한국교육과학기술부(학자금보증부)', '기초생활수급자 장학생(미래로 장학생)은 국내 고등교육기관의 학부에 재학 중인 대한민국 국적의 기초생활수급자이며 성적기준을 충족한 자를 대상으로 선발함. 등록금 범위 내 지원(입학금, 수업료, 기성회비 포함, 학생회비·기숙사비 제외), 등록금 납부 후 추후 환불 방식으로 지급됨. 미래로장학금이 등록금액보다 적을 경우 백마(B) 장학금을 함께 신청 가능. 이중수혜 원칙적으로 금지(모든 교내·교외 장학금, 학자금 대출)이며 봉사장학금 등 특별한 경우에 한하여 제한적으로 인정.', NULL, 'www.studentloan.go.kr', NULL, NULL, NULL, NULL, NULL, NULL, 3.6, 'semester', FALSE, NULL, 'korean_only', NULL, NULL, ARRAY['basic_livelihood_recipient'], '2009-02-27', '모든 학년 해당되며 수업연한초과자도 신청 가능', NULL, NULL, '직전학기 12학점 이상 이수(장애우 본인인 경우 이수학점 제한없음)', '신입생: 고교내신이수과목 1/2이상 6등급 이상 또는 수능 3개 영역(언어, 수리, 외국어)이 6등급 이상(예체능계는 언어,외국어영역이 모두 6등급 이내자)', NULL, '‘09. 2. 2(월) ~ 2. 27(금) (당초 09.1.30까지였으나 추가신청 09.2.27까지 가능)', NULL, NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('2009학년도 제1학기 기초생활 수급자장학금(미래로장학금)', '한국장학재단(학자금보증부)', '기초생활수급자 장학생(미래로 장학생)은 국내 고등교육기관의 학부에 재학 중인 대한민국 국적의 기초생활수급자 본인, 자녀 또는 손자녀이며 성적기준을 충족한 자를 대상으로 선발함. 등록금 범위 내 지원(입학금, 수업료, 기성회비, 단 학생회비·기숙사비 등은 제외)하며 미래로장학금이 등록금액보다 적을 경우 백마(B) 장학금을 함께 신청. 원칙적으로 타 교내외 장학금, 학자금 대출과 이중수혜 불가(봉사장학금 등 특별한 경우 제한적 인정).', NULL, 'www.studentloan.go.kr', NULL, NULL, NULL, NULL, NULL, NULL, 3.6, 'semester', FALSE, NULL, 'korean_only', NULL, NULL, ARRAY['basic_livelihood_recipient'], '2009-01-30', '수업연한내 모든 학년 해당', NULL, NULL, '직전학기 12학점 이상 이수', '신입생: 고교내신이수과목 1/2이상 6등급 이상 또는, 수능 3개 영역(언어, 수리, 외국어)이 6등급 이상', NULL, '신입생: ''09.1.9(금)~1.30(금) 11:30, 재학생: ''09.1.9(금)~1.22(목) 21:00', '충남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'national_scholarship'),
('일반대학원생 우수학술지 논문 게재 장려금', '충남대학교', '대학원생의 전문학술지 논문 게재를 장려하고 연구 활성화 및 연구의욕 고취를 위한 장려금. 2단계 BK21사업 SCI(E)급 우수학술지, 한국학술진흥재단 등재/등재후보 학술지, 국제저명·국제전문학술지(등재)에 주저자(First Author)로 게재한 논문이 대상이며, 논문 등급에 따라 차등 지원(SCI급 500,000원 내외, 기타 국제전문학술지(등재) 400,000원 내외, 한국학술진흥재단 등재 또는 등재후보 학술지 300,000원 내외). 1인이 복수 논문게재가 있을 경우 1회만 지급. 지원 대상 논문은 2008년 2월 1일~2009년 1월 31일 사이 게재(출판)된 논문.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'korean_only', NULL, NULL, '{}', '2009-02-04', NULL, NULL, '충남대학교 대학원', NULL, NULL, '00명', '2009. 1. 22(목) ~ 2. 4(수) 09:00~18:00 (평일에 한함)', '충남대학교', NULL, 'post_undergrad', NULL, NULL, NULL, 'school_internal', 'research'),
('2009 신라문화장학재단 장학생', '신라문화장학재단', '2009년도 2학년 예정자(6년제는 본과 2학년) 대상, 결격사유 없을 시 졸업까지 등록금 전액 장학금 지급. 서류전형(1차) 후 면접(2차)으로 선발.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4.0, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '2009-02-04', '2009년도 2학년 예정자 (6년제는 본과 2학년)', NULL, NULL, '32학점 이상 이수', NULL, NULL, '2009. 01. 19 ~ 2008. 2. 4 (우체국 소인 2월 4일까지 유효)', NULL, NULL, 'undergrad_enrolled', 2, 2, NULL, 'school_external', 'private_foundation'),
('2009학년도 신입생 장학금', '충남대학교', '2009학년도 신입생 대상 교내 장학금으로 보훈, 새터민지원, 외국어우수, 영탑A/B/C, 백마A/B/C, 국가장학 미래로 등 여러 종류로 구성됨. 각 장학명별 선발기준과 지급내역이 다름.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TOEIC', 900, ARRAY['national_merit','north_korean_defector','child_care_facility','basic_livelihood_recipient','near_poor'], '2009-01-30', '신입생', NULL, NULL, NULL, '고교내신이수과목 1/2이상 6등급 이상 또는, 수능 3개 영역(언어, 수리, 외국어)이 6등급 이상 (국가장학 미래로 항목)', '적격자 전원', '수시합격자: 2009.1.21.~2009.1.30 12:00까지, 정시합격자: 정시합격자 발표일~2009.1.30. 12:00까지', '충남대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'special_target'),
('2009. 1학기 정부보증 학자금대출', '충남대학교', '2009학년도 1학기 등록금 납부 대상자를 위한 정부보증 학자금대출 시행 안내. 신용관리정보가 없고 대출신청 금융기관에 연체중이 아닌 자만 대상이며, 공인인증서 발급, 학자금포탈사이트 대출신청, 서류제출, 기금승인, 대출약정 및 실행의 절차를 거침. 대출신청연령은 1953년 1월 1일 이후 출생자.', NULL, 'www.studentloan.go.kr', NULL, NULL, NULL, NULL, NULL, NULL, 3.15, 'semester', NULL, NULL, NULL, NULL, NULL, ARRAY['basic_livelihood_recipient'], '2009-03-30', NULL, NULL, NULL, '직전학기 이수학점 12학점 이상 (대학원생, 졸업학기 학생, 장애우 학생은 12학점 미만 이수자도 가능, 신입생은 요건 없음)', NULL, NULL, '2009. 1. 19.(월) ~ 2009. 3. 30.(월)', '충남대학교', NULL, NULL, NULL, NULL, NULL, 'school_external', 'national_scholarship'),
(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, '역사기행 [고구려 유적답사] 일정 및 오리엔테이션 안내 - 일정은 내부사정에 따라 약간 변경될 수 있으며, 오리엔테이션은 A팀 2007.10.29(월) 16시, B팀 2007.10.29(월) 17시, 장소는 대학본부 3층 소회의실(대회의실에서 변경됨)에서 진행됨.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, '충남대학교', '이 공고문은 장학금이 아니라 2007학년도 2학기 사회봉사 교과목 수강신청 및 봉사활동 신청 안내문임. 사회봉사 교과목은 현장 봉사활동을 하는 일반선택 실습과목으로 졸업이수 학점에 포함되며(해당학기 평점 계산에서는 제외), 졸업할 때까지 2차례 2학점까지 이수 가능. 한 학기 30시간 이상 실습해야 1학점 취득 가능하며 Pass/Fail로 평가됨. 이수자에게는 사회봉사인증서 수여 및 본교 주최 해외봉사활동 기회 우선 부여의 특전이 주어짐.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '가. 전산상 수강신청기간 : 2007. 8. 1(수) ~ 2007. 8. 6(수) / 나. 전산상 봉사활동신청기간 : 2007. 8. 3(금) ~ 2007. 8. 9(목)', '충남대학교', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('제 7회 윤동주 시문학상 공모', '연세대학교', '전국 대학(교) 학부생을 대상으로 자유주제 운문 5편을 응모받는 시문학상 공모전. A4 용지에 워드프로세서로 작성하며, 우편 또는 방문접수. 당선작 1명 300만원, 가작 2명 150만원 수상.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '2007-04-17', NULL, NULL, '전국 대학(교) 학부생', NULL, NULL, '당선작 1명, 가작 2명', '2007. 4. 10(화)~4. 17(화)', NULL, NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_external', 'private_foundation'),
('2007년 e-시정도우미 모집', '대전광역시', '시정발전 및 시책발전을 위한 제안으로 젊은 대전건설에 기여할 대학생을 모집. 활동내용: 시정발전 및 시책개발을 위한 참신한 아이디어 제안, 시민 여론 조사(설문 등) 및 생활 주변의 불편사항 제보, 홈페이지 모니터링 등. 활동기간은 1년(연임가능). 보상: 이츠대전등 시정관련 각종 홍보물 제공, 자원봉사 마일리지 혜택 부여(시정 제안·제보·건의·설문 1건당 자원봉사1시간인정), 연말 우수활동자 시장 표창장 수여(10명이내), 자원봉사 확인서 발급에 의한 학점 인정. 금전적 지원금이 아닌 자원봉사 마일리지/표창/학점 인정 등의 혜택이 주어지는 활동 모집 공고임.', NULL, 'http://www.metro.daejeon.kr/e_supporter', NULL, NULL, NULL, '대전', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '2007-02-28', NULL, NULL, NULL, NULL, NULL, '100명', '2007년 2월 15일 - 2월 28일', NULL, NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'support_fund', 'activity_participation_support'),
(NULL, '교육혁신위원회', '미래교육 설계를 위한 아이디어 공모전 참여 및 홍보협조. 우편 또는 이메일(meecho@nate.com) 접수.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '2007-02-15', NULL, NULL, NULL, NULL, NULL, NULL, '2006년 12월 30일~2007년 2월 15일', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, '학생재능개발클럽 최종 선발팀 명단 공지 - 학생들의 창의적 재능 발굴과 사업지원을 통해 창업 관련 실무능력을 향상할 수 있는 기회를 제공하고자 학생재능개발클럽을 선발하였다는 결과 공지 게시글로, 장학금 지원 조건이나 금액 등의 세부 내용은 포함되어 있지 않음', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, '대전 충남지방병무청', '육군 모집병 지원 자격 기준 확대 안내. 1. 기술행정병(의무병) 학력 기준: 종전 대학 2년 이상 수료자 → 변경 대학 학력 이수자, 실업계 고교 3년 수료자. 2. 공용화기병 신체등위 기준: 종전 신체등위 1~2급자 → 변경 신체등위 1~3급자. 적용시기: 2006년 11월 6일부터 시행.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('대전문화예술의 전당 2007 Winter Festival 공모', '대전문화예술의 전당', '대전지역 공연 비전문 예술단체 및 동호회들에게 공연기회 제공, 지역내 사회인 또는 대학 공연 관련 예술활성화 도모를 위한 공모. 공모를 통한 제출서류 심사와 단체제안 설명을 통하여 선정하며, 2007.1.15(월)~28(일) 중 공연 가능한 작품, 대전문화예술의 전당 아트홀(1,546석), 앙상블홀(651석)에서 공연가능한 작품, 연극·무용·음악 등 모든 장르 대상. 우편접수는 받지 않으며 직접방문접수만 가능.', NULL, 'www.djac.or.kr', NULL, NULL, NULL, '대전', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '2006-11-03', NULL, NULL, NULL, NULL, NULL, NULL, '2006.10.30(월)~11.3(금)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('충남대학교 학생재능개발클럽 모집', '충남대학교', '학생들에게 잠재해 있는 창의적 재능 발굴과 그에 대한 사업 지원을 통해 창업 관련 실무능력을 향상할 수 있는 기회를 제공. 지원내용: 공간 제공(산학연교육연구원 6층), 기본 설비 및 기자재 지원, 설립 및 운영에 관한 지도 또는 자문. 모집분야: 영상·그래픽 디자인, 행사기획, 웰빙식품, 문화·예술, 광고, 실버산업, 마케팅, 특허, 의류·패션 및 기타 분야. 제출서류: 등록신청서, 사업계획서, 회원명단, 소요설비 및 기자재 목록. 분야선정은 소정의 심사기준과 운영 상황에 따라 추후 결정.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', '2006-11-10', NULL, NULL, NULL, NULL, NULL, NULL, '2006. 9. 18(월) ~ 11. 10(금)', '충남대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit');
