-- 우송대학교 장학금
-- supabase/scholarship_dedup_list.md 기준, 배치별로 아래에 이어서 추가함.
-- 참고용 데이터 백업 스크립트 — 새 DB에 재적재할 때 사용 (id는 SERIAL이라 자동 재할당됨)

-- 배치 1: 교내장학제도 (대학 전체 대상) (16건, id 200~215)
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('자립장학금', '우송대학교', '직전학기 성적 85점(100점 만점) + 우송지수 10점 + 인성 5점 합산 기준 대상. 등록금 전액 감면. 100점 만점 백분위·자체 지수 혼합 기준이라 GPA 필드로 환산 불가.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('단정장학금', '우송대학교', '성적 우수자 대상(자립장학금 다음 등급). 등록금 2/3 감면.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('독행장학금', '우송대학교', '성적 우수자 대상. 등록금 1/3 감면.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('협동장학금', '우송대학교', '성적 우수자 대상. 등록금 1/6 감면.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('해외연수장학금(일본/영어권)', '우송대학교', '해외연수(일본·영어권) 선발 학생 대상. 등록금 3/4 범위 내 학비 지급.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'international_exchange'),
('해외연수장학금(아시아권)', '우송대학교', '해외연수(아시아권) 선발 학생 대상. 등록금 2/3 범위 내 학비 지급.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'international_exchange'),
('해외인턴십장학금', '우송대학교', '해외인턴십 선발 학생 대상. 등록금 1/2 지급.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'international_exchange'),
('국가유공자장학금(우송대)', '우송대학교', '국가유공자(본인/자녀 등) 대상. 평점 1.69 이상 유지 조건. 등록금 전액 면제.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, 1.69, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('우송가족장학금', '우송대학교', '2인 이상 직계가족이 동시 재학 중인 학생 대상.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('재해장학금(우송대)', '우송대학교', '재해 발생 학생 대상, 교무위원회 심의 후 지급.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('대외학술활동장학금', '우송대학교', '국제·전국 규모 경시·경연대회 입상자 대상. 1등 50만원, 2~3등 30만원, 지역대회 10만원.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('체육특기자장학금(우송대)', '우송대학교', '체육특기자 전형 입학생 대상, 경기 수상실적 고려하여 차등 지급.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('학군사관후보생장학금(우송대)', '우송대학교', '학군단(ROTC) 후보생 대상. 대대장 100%, 참모·소대장 70%, 일반 50% 등록금 지원 + 기숙사비 전액 면제.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('외국인유학생장학금(우송대)', '우송대학교', '외국인 유학생 대상. 평점 4.3 이상 등록금 100%, 4.15 이상 70%, 3.0 이상 30%(4.5만점 기준).', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('개발도상국 정부추천 장학금', '우송대학교', '개발도상국 정부 추천을 받은 외국인 유학생 대상. 등록금 전액 면제.', NULL, 'https://ent.wsu.ac.kr/page/index.jsp?code=efix0302', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('우송장학생', '우송대학교', '1~4학년 재학생 중 직전학기(들) 15학점 이상 취득·F학점 없음 + 다음 중 하나 충족: 전체 평점평균 4.00 이상(4.5만점), 국제/전국 규모 경시대회 3위 이내 입상, 외국어성적 우수(TOEIC 850점 이상 등), 글로벌 리더(별도 선발). 선발 시 국내연수 1회+해외연수 1회 기회 제공. 여러 자격경로 중 하나만 맞으면 되는 OR 조건이라 GPA 하나로 필터링하면 다른 경로 해당자를 놓침.', NULL, 'https://wsjanghak.wsu.ac.kr/page/index.jsp?code=wsjanghak0104a', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '직전학기(들) 15학점 이상, F학점 없음', NULL, NULL, '매 학기 초 공지 (우송대 홈페이지 확인)', '우송대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit');
