-- 목원대학교 장학금
-- supabase/scholarship_dedup_list.md 기준, 배치별로 아래에 이어서 추가함.
-- 참고용 데이터 백업 스크립트 — 새 DB에 재적재할 때 사용 (id는 SERIAL이라 자동 재할당됨)

-- 배치 1: 교내장학제도 (대학 전체 대상) (25건, id 175~199)
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('학과수석장학금', '목원대학교', '각 학부(과)별 직전학기 평점평균 최고 성적자 대상. 평점 3.5 이상, 17학점 이상 취득. 등록금 100% 감면.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, 3.5, NULL, NULL, NULL, NULL, NULL, '17학점 이상', NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('학년수석장학금', '목원대학교', '학과 내 학년별 최우수 성적자 대상. 등록금 80% 감면.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('성적우수장학금(목원대)', '목원대학교', '학과/학년별 우수 성적자 대상. 등록금 50%/35%/20% 감면(등급별 차등).', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('창의인재장학금', '목원대학교', '복수전공·융복합전공을 이수 중인 학생 대상. 등록금 범위 내 지급.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('목원희망장학금', '목원대학교', '한국장학재단 소득분위 0~8분위 국가장학금 신청자 대상. 직전학기 평점평균 2.6 이상.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, 8, 2.6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('모범장학금(A)', '목원대학교', '학부(과)장 추천 학생 대상. 직전학기 평점평균 1.6 이상.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, 1.6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('보훈장학금(목원대)', '목원대학교', '국가유공자 본인·배우자·직계자녀 대상. 입학금 및 등록금 전액 감면.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('목원곰두리장학금', '목원대학교', '장애인 등록 학생 대상. A급 100만원, B급 70만원(등급별 차등).', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('교직원복지장학금(목원대)', '목원대학교', '교직원 직계자녀 대상. 직전학기 평점평균 2.5 이상. 등록금 전액 감면.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, 2.5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('새터민장학금(목원대)', '목원대학교', '북한이탈주민 대상. 등록금 전액 감면.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('다문화가정지원장학금(목원대)', '목원대학교', '다문화가정 학생 대상. 50만원 지급.', 500000, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('사회봉사장학금(목원대)', '목원대학교', '학기당 봉사활동 120시간 이상 수행한 학생 대상. 50만원 지급.', 500000, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('글로벌리더장학금', '목원대학교', '대외 활동 등으로 대학의 명예를 선양한 학생 대상(성적 제한 없음). 선정 기준이 사례별 심의라 구조화된 조건 없음.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('세종대왕장학금', '목원대학교', '외국인 유학생 대상. 등록금 40% 이상 감면.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('학생부교과전형장학금(신입생)', '목원대학교', '수시 학생부교과전형 수석합격자 대상. 4년간 등록금 전액+기숙사비 지원(2년차부터 평점 3.5 이상 유지 조건).', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('단과대학수석장학금(신입생)', '목원대학교', '수시 교과전형 등 단과대학 수석합격자 대상. 1년 등록금 전액(2년차부터 평점 3.5 이상 유지 조건).', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('학부(과)수석장학금(신입생)', '목원대학교', '각 학부 수시전형 수석합격자 대상. 1학기 등록금 70% 지원.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('학생부종합전형장학금(신입생)', '목원대학교', '수시 학생부종합전형 수석합격자 대상. 1년 등록금 전액(2년차부터 평점 3.5 이상 유지 조건).', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('스톡스장학금', '목원대학교', '정시모집 수능 국어·수학·영어 모두 1등급 대상. 4년 등록금 전액+학업장려금 연 320만원(2년차부터 평점 3.5 이상 유지 조건).', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수능 국어·수학·영어 모두 1등급', NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('감리교학원 이사장장학금', '목원대학교', '정시모집 수능 3과목 합 4등급 이내 대상. 4년 등록금 전액+연 120만원(2년차부터 평점 3.5 이상 유지 조건).', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수능 3과목 합 4등급 이내', NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('목원대학교 총장장학금', '목원대학교', '정시모집 수능 3과목 합 5등급 이내 대상. 4년 등록금 전액+연 80만원(2년차부터 평점 3.5 이상 유지 조건).', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수능 3과목 합 5등급 이내', NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('실기우수장학금(목원대)', '목원대학교', '음악·미술 등 실기전형 입상자 대상. 1위 4학기, 2위 2학기, 3위 1학기 등록금 100% 지원.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'activity_merit'),
('영어능력우수장학금', '목원대학교', 'TOEIC 900점 이상 또는 TOEFL IBT 100점 이상 신입생 대상. 1학기 등록금 전액 지원. 시험 종류·점수 조건이라 현재 시스템 필드로는 매칭 불가.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('목원사랑 동문장학금', '목원대학교', '부모 모두 목원대학교 졸업생인 신입생 대상. 첫 학기 100만원 지급.', 1000000, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'special_target'),
('목원스타트장학금', '목원대학교', '신입생 대상. 최초합격 1학기 80만원 감면, 충원합격 1학기 40만원 감면.', NULL, 'https://www.mokwon.ac.kr/kr/html/sub04/0401.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (목원대 홈페이지 확인)', '목원대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit');
