-- 한국침례신학대학교(KBTUS) 장학금
-- supabase/scholarship_dedup_list.md 기준 신규 배치. id는 SERIAL이라 실제 INSERT 시 자동 재할당됨
-- (여기서는 id 값을 지정하지 않음 -- 라이브 DB에 실제로 넣을 때 SERIAL이 알아서 채번).
--
-- 출처: 한국침례신학대학교 공식 홈페이지(kbtus.ac.kr) 학사안내>장학안내 섹션.
--   - 교내장학금 목록: http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303
--   - 교외장학금 목록: http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN310
--   - 장학공지사항 게시판: http://www.kbtus.ac.kr/kor/CMS/Board/Board.do?mCode=MN170
-- 위 두 페이지는 CNU의 support_030302.html과 같은 성격의 "제도 통합 정적 안내 페이지"라
-- 개별 신청기간이 명시되어 있지 않음. 공통 자격기준(장학금지급규정 제8조): 예배출석 P등급,
-- 직전학기 평점평균 2.5 이상, 과락(F) 없음 -- 자세한 내용은 kbtus_progress.md 참고.
--
-- GPA 스케일: 4.5만점제 확인(공식 페이지 mCode=MN140), 다만 등급별 고정값이 아니라 구간제
-- (A+=4.31~4.5 등)라 다른 대전권 대학과 표기 방식이 다름 -- 상세 내용 kbtus_progress.md 참고.
-- 이번 배치의 모든 min_gpa 값은 학교 자체 4.5만점 기준 원문 숫자(예: "2.5 이상")를 그대로 저장함.

-- 배치 1: 중앙 교내/교외 장학금 통합 페이지 (45건)
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('침신사랑장학금', '한국침례신학대학교', '동일 교회에서 신입생 3명 이상이 동시에 입학할 경우, 담임목사 추천을 받은 1명에게 지급. 수업료 100%. 제출서류: 교회주보, 재직증명서, 목회자추천서.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '신입학 시 선발 (한국침례신학대학교 입학처/학생지원팀 공지 확인)', '한국침례신학대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'special_target'),
('침례교사모장학금', '한국침례신학대학교', '침례교단 인준 목회자의 배우자(사모) 대상. 수업료 13% 지원. 제출서류: 재직증명서, 가족관계증명서.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, 2.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (장학금지급규정 제8조: 예배출석 P등급·직전학기 평점평균 2.5 이상·과락 없음)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('목회자(자녀)장학금(침례신학대)', '한국침례신학대학교', '침례교단 또는 타 교단 인준 목회자의 자녀(만 33세 미만) 대상. 수업료 30% 지원. 1개 학위과정에 한해 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, 33, NULL, NULL, NULL, NULL, 2.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (장학금지급규정 제8조 공통기준 적용)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('해외선교사(자녀)장학금(침례신학대)', '한국침례신학대학교', '한국침례회 해외선교회 소속 장기선교사(북한 선교사 포함)의 자녀 대상. 수업료 50% 지원.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, 2.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (장학금지급규정 제8조 공통기준 적용)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('세가족장학금(침례신학대)', '한국침례신학대학교', '직계가족 3인 이상이 학부·대학원에 동시 재학 중인 경우 가족이 지정한 1인에게 지급. 수업료 65%.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, 2.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (장학금지급규정 제8조 공통기준 적용)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('부부장학금(침례신학대)', '한국침례신학대학교', '부부가 동시 재학 중인 경우 지정한 1인에게 지급. 수업료 50%.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, 2.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (장학금지급규정 제8조 공통기준 적용)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('교직원자녀장학금(침례신학대)', '한국침례신학대학교', '한국침례신학대학교 교직원의 자녀(만 33세 미만) 대상. 수업료 100%. 1개 학위과정에 한해 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, 33, NULL, NULL, NULL, NULL, 2.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (장학금지급규정 제8조 공통기준 적용)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('교직원(배우자)장학금(침례신학대)', '한국침례신학대학교', '한국침례신학대학교 교직원 본인 또는 그 배우자 대상. 수업료 50%. 1개 학위과정에 한해 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, 2.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (장학금지급규정 제8조 공통기준 적용)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('북한이탈주민장학금(침례신학대)', '한국침례신학대학교', '북한이탈주민 재학생 대상(교내 자체 재원). 수업료 50% 지원. 참고: 홈페이지 교외장학금 목록에도 통일부 관련 법령 근거의 동명 국가지원 프로그램이 별도로 안내되어 있으나, 대학 무관 전국공통 성격이라 이번 배치에서는 이 교내 자체 재원 항목만 채택함(중복 방지).', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, 2.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (장학금지급규정 제8조 공통기준 적용)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('보훈장학금(침례신학대)', '한국침례신학대학교', '국가유공자 본인 또는 배우자는 수업료 100%, 국가유공자 자녀는 직전학기 성적 백분위 70점 이상인 경우 수업료 50% 지원(교내 자체 재원).', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '백분위 70점 이상(자녀에 한함, 100점 만점 기준이라 min_gpa로 환산 불가)', NULL, '매 학기 말 시험기간 중 신청 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('해외교환학생장학금(침례신학대)', '한국침례신학대학교', '해외 교환학생으로 선발된 학생 대상, 장학위원회 심의로 선발·금액 결정.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 국제교류 관련 공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'international_exchange'),
('국외학생장학금(침례신학대)', '한국침례신학대학교', '외국인 학생 대상(국외 한국인 대상 교육 장학금 미수혜자에 한함). 수업료 40% 지원, 최대 2개 학위과정까지 지급. 제출서류: 여권, 목회자추천서, 건강보험 가입증명.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('침신곰두리장학금', '한국침례신학대학교', '중증장애 학부 재학생 대상. 수업료 50% 지원. 최대 8명 이내 선발, 1개 학위과정에 한해 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, '8명 이내', '매 학기 말 시험기간 중 신청 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('전공실기장학금(침례신학대)', '한국침례신학대학교', '교회음악과 학생 중 학과 교수 추천을 받은 자 대상. 수업료 100% 지원.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '교회음악과', NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', '교회음악과', NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('군종사관후보생장학금(침례신학대)', '한국침례신학대학교', '국방부에서 선발한 군종사관후보생 대상. 수업료 100% 지원. 제출서류: 선발확인서.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('학생임원장학금 A(침례신학대)', '한국침례신학대학교', '총학생회장·부회장·총무 등 최상위 학생자치기구 임원 대상. 수업료 100% 지원.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('학생임원장학금 B(침례신학대)', '한국침례신학대학교', '학과 학생회장·동아리연합회장 등 중간급 학생자치기구 임원 대상. 수업료 70% 지원.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('학생임원장학금 C(침례신학대)', '한국침례신학대학교', '학생회 국장·학과 총무 등 실무진 학생자치기구 임원 대상. 수업료 30% 지원.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('교수학습지원장학금(침례신학대)', '한국침례신학대학교', '교수학습지원센터의 추천을 받은 학생 대상(각종 대회 격려 포함). 지급액은 프로그램별로 상이.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 교수학습지원센터 공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('취창업지원장학금(침례신학대)', '한국침례신학대학교', '진로·취업지원센터의 추천을 받은 학생 대상(각종 대회 격려 포함). 지급액은 프로그램별로 상이.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 진로·취업지원센터 공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('대회참가 격려장학금(침례신학대)', '한국침례신학대학교', '각종 대회·경연 참가자 중 소속 학과 추천을 받은 학생 대상. 지급액은 대회별로 상이.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('외국어능력우수장학금(침례신학대)', '한국침례신학대학교', 'TOEFL IBT 90점(120점 만점) 이상, TOEIC 850점(990점 만점) 이상, 또는 TOEIC Speaking 중상급(Intermediate-High) 이상 등 어학 성적 우수자 대상. 수업료 40%(1개 학기에 한함). 시험 종류·점수 조건이라 현재 시스템 필드로는 구조화된 매칭 불가(matching_gaps.md #10 참고).', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('신입생 성적우수장학금(침례신학대)', '한국침례신학대학교', '입학성적(전형 환산점수) 상위 5% 신입생 대상 — 과수석(수업료 100%), 성적우수A(수석 포함 상위 3%, 수업료 65%), 성적우수B(다음 2%, 수업료 25%) 3단계로 차등 지급. 사회복지학과·유아교육과 등 일부 학과는 별도 트랙으로 선발.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '입학전형 환산점수 상위 5% 이내', NULL, '신입학 시 선발 (한국침례신학대학교 입학처/학생지원팀 공지 확인)', '한국침례신학대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('수학능력시험우수장학금(침례신학대)', '한국침례신학대학교', '대학수학능력시험 국어·수학·영어 전 영역 1등급(예체능계열 제외) 신입생 대상. 4년간 수업료 100% 지원.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수능 국어·수학·영어 전 영역 1등급', NULL, '신입학 시 선발 (한국침례신학대학교 입학처/학생지원팀 공지 확인)', '한국침례신학대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('재학생 성적우수장학금(침례신학대)', '한국침례신학대학교', '매년 성적 상위 5% 재학생 대상 — 과수석(수업료 100%), 성적우수A(수석 포함 상위 3%, 수업료 65%), 성적우수B(다음 2%, 수업료 25%) 3단계로 차등 지급. 순위 기준 선발이라 min_gpa 단일 수치로 표현하지 않음(과대매칭 방지).', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매년 성적순위 상위 5% 이내', NULL, '매 학기 말 시험기간 중 신청 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('특별비전장학금(침례신학대)', '한국침례신학대학교', '2026학년도 신입학·편입학생 대상 1년간 한정 지원(가정형편 고려). 수업료 이내에서 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '신입학·편입학 시 선발 (한국침례신학대학교 학생지원팀 공지 확인)', '한국침례신학대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'welfare_living'),
('침신비전장학금', '한국침례신학대학교', '가정형편이 어려운 재학생 대상. 수업료 이내에서 장학위원회 심의로 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, 2.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (장학금지급규정 제8조 공통기준 적용)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('교내대응장학금(침례신학대)', '한국침례신학대학교', '한국장학재단 국가장학금 수혜자 대상, 장학위원회 심의를 거쳐 교내 재원으로 대응 지원. 수업료 이내.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 국가장학금 신청과 연동 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('재난위로지원장학금(침례신학대)', '한국침례신학대학교', '국가재난 발생 시 장학위원회 심의로 지급 대상·금액 결정. 통상 요구되는 GPA·출석 기준이 면제됨.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '국가재난 발생 시 수시 공지', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('피영민문영숙후원 기념장학금', '한국침례신학대학교', '목회자 자녀 및 생계가 곤란한 학생 대상(총장·학과장·대학원장 추천 필요). 100만원 이내 지급, 장학사정관 심의.', 1000000, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('모영국송정선목사 부부장학금', '한국침례신학대학교', '장학사정관 심의로 선발. 100만원 이내 지급. 목회자 부부(모영국·송정선 목사)를 기리는 기금장학금.', 1000000, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('겨자씨장학금', '한국침례신학대학교', '장학사정관 심의로 선발·금액 결정(구체적 자격조건 명시 없는 재량형 기금장학금).', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('손말숙여사기념장학금', '한국침례신학대학교', '신학대학원생 중 성적이 우수하고 교회 사역 중이며 가정형편이 어려운 학생 대상. 등록금 이내 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '신학', NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 대학원 공지 확인)', '한국침례신학대학교', '신학대학원', 'post_undergrad', NULL, NULL, 'masters', 'school_internal', 'special_target'),
('성구이기념장학금', '한국침례신학대학교', '신학대학원생 중 성적이 우수하고 가정형편이 어려운 학생 대상. 등록금 이내 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '신학', NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 대학원 공지 확인)', '한국침례신학대학교', '신학대학원', 'post_undergrad', NULL, NULL, 'masters', 'school_internal', 'welfare_living'),
('최현숙전도사기념장학금', '한국침례신학대학교', '학부생 중 성적이 우수하고 가정형편이 어려운 학생 대상. 등록금 이내 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 시험기간 중 신청 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('김성진전도사기념장학금', '한국침례신학대학교', '신학대학원생 중 성적이 우수하고 교회 사역 중이며 가정형편이 어려운 학생 대상. 등록금 이내 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '신학', NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 대학원 공지 확인)', '한국침례신학대학교', '신학대학원', 'post_undergrad', NULL, NULL, 'masters', 'school_internal', 'special_target'),
('민유선교수기념장학금', '한국침례신학대학교', '침례교 해외선교회 소속 선교사의 자녀로 신학계열 학부 또는 대학원에 재학 중인 학생 대상. 등록금 이내 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '신학계열(학부·대학원)', NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('서동숙사모기념장학금', '한국침례신학대학교', '일반대학원 기독교교육전공 재학생 대상. 등록금 이내 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '기독교교육전공', NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 대학원 공지 확인)', '한국침례신학대학교', '일반대학원', 'post_undergrad', NULL, NULL, 'masters', 'school_internal', 'special_target'),
('이요한용담기념장학금', '한국침례신학대학교', '장학사정관 심의로 선발·금액 결정(구체적 자격조건 명시 없는 재량형 기금이자장학금). 등록금 이내 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('전복단권사이창식집사 기념장학금', '한국침례신학대학교', '목회자 또는 선교사를 지망하는 학생 대상. 등록금 이내 지급. 향후 목회·선교 사역 지망이라는 진로 조건이라 현재 시스템 필드로는 구조화된 매칭 불가(진로 지향 조건).', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN303', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('채플장학금(침례신학대)', '한국침례신학대학교', '대학예배(채플) 출석이 우수한 학생 대상. 10만원 지급.', 100000, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN310', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('성적향상장학금(침례신학대)', '한국침례신학대학교', '직전 학기 대비 성적이 향상된 학생 대상. 20만원~50만원 차등 지급(향상폭 기준이라 min_gpa 단일 수치로 표현 불가).', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN310', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 말 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('BTS장학금(성경시험, 침례신학대)', '한국침례신학대학교', '성경시험(Bible Test Scholarship) 성적 우수자 대상. 20만원~100만원 차등 지급.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN310', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 성경시험 시행 후 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('태성장학금', '한국침례신학대학교', '규정에 따라 선발(세부 자격조건 원문에 구체적으로 명시되어 있지 않음). 수업료 100% 지원.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN310', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 공지 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', NULL),
('지정·미지정 외부장학금(침례신학대)', '한국침례신학대학교', '기부자가 특정 대상을 지정하거나(지정), 지정 없이 장학사정관 심의로 배정(미지정)하는 기부금 기반 장학금 범주. 특정 학생이 신청 가능한 단일 프로그램이 아니라 매년 기부 상황에 따라 달라지는 포괄 범주라 조건이 매우 불명확함 — 참고용으로만 등록.', NULL, 'http://www.kbtus.ac.kr/kor/CMS/Contents/Contents.do?mCode=MN310', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수시 (한국침례신학대학교 학사공지 확인)', '한국침례신학대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', NULL);
