-- 을지대학교 장학금
-- supabase/scholarship_dedup_list.md 기준, 배치별로 아래에 이어서 추가함.
-- 참고용 데이터 백업 스크립트 — 새 DB에 재적재할 때 사용 (id는 SERIAL이라 자동 재할당됨)
--
-- 범위: 대전캠퍼스(의과대학, 의예과/의학과 단일학과 구조) + 대학 전체(전 캠퍼스) 공통 교내장학금 제도.
-- 을지대학교는 대전/성남/의정부 3개 캠퍼스 체제이며, 대전캠퍼스에는 의과대학 1개 대학만 설치되어
-- 있음(간호대학·보건과학대학·바이오융합대학·미래융합대학 등은 전부 성남/의정부캠퍼스 소속).
-- 출처: https://www.eulji.ac.kr/?menuno=3143 (학사안내>장학정보>장학금>교내장학금, 정적 이미지 페이지
-- "교내 장학금 제도")와 https://medicine.eulji.ac.kr/?menuno=3311 (의과대학 자체 장학안내, 동일 표를
-- 재게시한 것으로 확인 — 의과대학 고유의 동문/기부자 명의 장학금은 발견되지 않음).
-- GPA 환산: 2026-08-02 공식 학칙 제49조로 확인 완료 — 4.5만점제, 고정값(A+=4.5/A0=4.0/B+=3.5/
-- B0=3.0/C+=2.5/C0=2.0/D+=1.5/D0=1.0/F=0). 대전권 다른 사립대(충남대·한밭대·배재대·목원대·
-- 우송대·한남대)와 동일한 4.5만점제·A0=4.00으로 확인됨 — 재수정 불필요.
-- min_gpa_basis: 중앙 표에 명시된 대로 전부 "직전학기" 기준이라 'semester'로 채움(단, 일부 항목은
-- "전체학기 및 직전학기" 둘 다 요구하는 AND 조건이라 완전히 표현 안 됨 — 각 항목 description 참고).

-- 배치 1: 교내장학금 제도 (대학 전체 공통, 대전캠퍼스 의과대학 포함) (20건)
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('학업성적우수장학금', '을지대학교', '직전학기 취득학점 12학점 이상·평점평균 2.0 이상(인정성적 기준 적용, P/NP 포함) 재학생 대상. 학과(전공) 재학생 인원 규모(10~24명/~29명/~50명/~99명/~120명/121~159명/160~190명)별로 순위(1등 최우수~8등 성적우등)에 따라 등록금 전액~1/7까지 차등 지급(인원이 많을수록 선발 인원·등수 구간 확대). 학과 내 상대순위 기반 선발이라 특정 평점평균 숫자(min_gpa)로는 표현 불가.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('학업성적향상(Jump-up)장학금', '을지대학교', '직전학기 대비 평점평균(GPA) 1.0 이상 향상된 재학생 대상. 향상폭 기준이라 min_gpa(절대 기준)로는 표현 불가. 50만원 지급.', 500000, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('면학장학금(을지대학교)', '을지대학교', '당해학기 국가장학금 신청자 중 소득구간 및 성적 기준(직전학기 평점평균 2.0 이상) 충족자 대상. 기초생활수급자·차상위계층은 등록금 전액, 소득분위 1~2구간 또는 8구간 이내 다자녀가구는 등록금 1/2, 소득분위 3~5구간은 150만원 지급(8구간 다자녀가구 특례는 max_income_bracket 필드로 표현 불가하여 여기 텍스트로만 기록).', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, 5, 2.0, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('을지가족장학금', '을지대학교', '본교에 재직하는 교직원(비전임교원·강사 제외)의 직계자녀 또는 노원을지대학교병원·의정부을지대학교병원(의료법인)·학교법인 재직자의 자녀는 등록금 1/2, 본교 졸업생의 자녀는 1인당 100만원, 가족(형제·자매·남매) 2인 이상이 재학 중(휴학자 제외)이면 1인당 50만원 지급. 소속 교직원/졸업생의 자녀 여부는 현재 시스템 필드로 매칭 불가.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('보훈장학금(을지대학교)', '을지대학교', '국가보훈처 지정 보훈대상자 및 그 직계자녀(보훈관련 법령에 의함) 대상. 직전학기 평점평균 2.0 이상 및 대학수업료 등 면제증명서 증빙 시 등록금 전액 지급.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, 2.0, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('새터민(북한이탈주민)장학금(을지대학교)', '을지대학교', '북한이탈주민(본인 또는 그 자녀 포함, 북한이탈주민법 기준 준수) 대상. 직전학기 평점평균 2.0 이상 및 교육지원대상자 증명서·북한이탈주민등록확인서 증빙 시 등록금 전액 지급.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, 2.0, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('장애장학금(을지대학교)', '을지대학교', '장애인등록증으로 증빙되는 장애 학생 본인 대상. 장애정도가 심한 학생(중증)은 등록금 2/3, 심하지 않은 학생(경증)은 등록금 1/2 지급.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('중증장애인자녀장학금(을지대학교)', '을지대학교', '중증장애인의 자녀인 재학생 대상(가족관계증명서, 장애인등록증(부모) 증빙). 본인이 아닌 부모의 장애가 기준이라 requires_disability(본인 장애 여부)로는 표현 불가 — matching_gaps.md의 "장애가 있는 부모 자녀"(disabled_parent) 케이스와 동일한 성격. 100만원 지급.', 1000000, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('외국인(소수학생)장학금(을지대학교)', '을지대학교', '순수 외국인으로 입학했거나 순수 외국인(외국인유학생)인 재학생 대상, 한국어능력시험(TOPIK) 서류 증빙. 직전학기 평점평균 4.0 이상은 등록금 최소 50% 지원(토픽 성적별 차등, 예: 토픽 6급 80% 감면~), 3.0 이상은 최소 30% 지원(토픽 성적별 차등), 2.0 이상~3.0 미만은 등록금 1/5(20%) 지원. 세종학당 중급2 이수자는 토픽4급, 중급1 이수자는 토픽3급에 준하여 인정, 법무부 사회통합프로그램 이수자도 인정. 시험 종류+점수 조합에 따른 세부 차등이라 구조화된 필드로 완전히 표현 불가.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, 2.0, 'semester', NULL, 'foreigner_only', NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('다문화장학금(을지대학교)', '을지대학교', '다문화가정의 자녀인 재학생 대상(부모 중 한 사람 이상이 외국인 또는 귀화자, 가족관계증명서·국적확인서류 증빙). 100만원 지급.', 1000000, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('리더십(학생간부)장학금', '을지대학교', '학생자치기구 간부 대상 — 총학생회장·부총학생회장은 등록금 전액, 단과대 학생회장(학생연합협의회장)은 등록금 3/4, 학과 학생회장·총학생회 부장은 등록금 2/3, 총학생회 차장은 등록금 1/3, 홍보대사 "바탕"은 개인실적반영 최대 150만원 지급.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('공로장학금(을지대학교)', '을지대학교', '학생자치기구 및 특별기구 등에서 학교·학과를 위해 활동하는 자 대상 — 학과/학년/반별 반대표는 40만원, 캠퍼스별 사생대표는 30만원, 학보사 편집장(3개 캠퍼스 통합 1명)은 등록금 2/3, 학보사 기자(각 캠퍼스별)·홍보대사 "뉴미디어"는 개인실적반영 최대 150만원 지급.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('을지한마음봉사장학금', '을지대학교', '학생봉사단 "빛길" 활동자는 개인실적반영 최대 150만원, 재학 중 누적봉사시간 300시간 이상(봉사활동 확인서 증빙)인 재학생은 100만원 지급.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('진학장학금(일현육성)', '을지대학교', '졸업 후 본교 대학원 진학을 확정한 재학생 대상(재학 중 본교 대학원 합격증 등 서류 증빙). 직전학기 평점평균 3.0 이상 시 등록금 전액 지급.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('차세대의료인장학금(일현육성)', '을지대학교', '의학과 M3, M4, M5, M6 재학생 중 졸업 후 재단병원(을지병원네트워크)에서 근무하려는 자 대상. 전체학기 및 직전학기 평점평균 각각 2.5 이상 시 등록금 전액 지급(전체누적+직전학기 둘 다 충족해야 하는 AND조건이라 min_gpa_basis 단일값으로 완전히 표현 안 됨, 안전하게 비워둠). 졸업 후 재단병원 근무 의사가 전제된 장학금(사용자 확인 후 포함 확정, 2026-08-02) — eligible_college를 의과대학으로 좁혀서 의료 계열 학생에게만 노출되도록 함.', NULL, 'https://medicine.eulji.ac.kr/?menuno=3311', NULL, NULL, NULL, NULL, NULL, NULL, 2.5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', '의과대학', 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'special_target'),
('어학성적우수장학금(을지대학교)', '을지대학교', '재학 중 공인 어학성적 우수자(TOEIC 950, TOEFL 110, TEPS 500, HSK 6급, JLPT 1급 이상) 대상. 시험 종류+점수 조합이라 현재 시스템 필드로는 매칭 불가. 100만원 지급.', 1000000, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('을지홍보장학금', '을지대학교', '재학생의 대학 및 재단 홍보 활동 장려 장학(뉴미디어·바탕 홍보대사 활동자 제외) — 대학 및 재단 홍보활동(SNS 게시물 등록 및 오프라인 활동 등) 우수자, 정량+정성 평가 후 최대 50만원 지급.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('HUMAN인재장학금', '을지대학교', '을지대 HUMAN 핵심역량 인증제(Humanistic(인문)/Universal(글로벌)/Multidisciplinary(창의융합)/Altruistic(봉사헌신)/Networking(소통협업) 5개 영역) 중 우수 인증을 받은 재학생 대상, 영역당 30만원 지급. 학교 자체 비교과 역량인증 프로그램이라 구조화된 매칭 불가(2026-08-01 사용자 확정 방침 — matching_gaps.md 11번 참고).', 300000, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit'),
('총장특별장학금(을지대학교)', '을지대학교', '재학 중 학교 발전에 크게 공헌하거나 명예를 빛낸 공로가 인정된 자(장관·지자체장급 또는 이에 준하는 수상실적자, 국제규모 각종대회 수상자, 교외 선행/봉사/표창 수상자 등), 재해·긴급한 경제적 어려움 등 지원이 필요하다고 판단되는 자, 그 밖에 총장이 특별한 사유를 인정하는 자에게 사안별 심사 후 지급. 지급액은 사안에 따라 상이.', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('마일리지장학금(을지대학교)', '을지대학교', '대학에서 지정한 비교과 프로그램에 참여하고 마일리지 장학금을 신청한 재학생 대상(최소 100~최대 300 마일리지 신청 가능, 1마일리지당 1,500원 환산 — 최대 45만원). 비교과 프로그램 참여 실적 기반이라 구조화된 매칭 불가(matching_gaps.md 11번 참고).', NULL, 'https://www.eulji.ac.kr/?menuno=3143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (을지대학교 홈페이지 확인)', '을지대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'activity_merit');
