-- 배재대학교 장학금
-- supabase/scholarship_dedup_list.md 기준, 배치별로 아래에 이어서 추가함.
-- 참고용 데이터 백업 스크립트 — 새 DB에 재적재할 때 사용 (id는 SERIAL이라 자동 재할당됨)

-- 배치 1: 교내장학제도 (대학 전체 대상, 19건, id 154~172)
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('배재아펜젤러장학금', '배재대학교', '신입생 전체수석 대상. 4년간 등록금 전액 지원(2년차부터는 평점평균 3.7 이상 유지 조건).', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, 3.7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('배재하워드장학금', '배재대학교', '수능성적 우수자(국어·수학 3등급, 영어 2등급) 대상. 1년~4년 등록금 전액 지원(등급별 차등).', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '수능 국어·수학 3등급, 영어 2등급', NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'academic_merit'),
('특기(경연)장학금', '배재대학교', '신입생 중 경연대회 입상자 대상. 1년 등록금 전액~50% 지원(입상 등급별 차등).', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'activity_merit'),
('체육특기장학금', '배재대학교', '체육특기자 전형 입학생 대상. 입학학기 등록금 전액 지원.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, 1, 1, NULL, 'school_internal', 'activity_merit'),
('만학도장학금', '배재대학교', '만 30세 이상 입학생 대상. 입학 후 최초학기 등록금 전액 지원.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('편입학장학금', '배재대학교', '편입학생 대상, 전적대학 성적 기준으로 등급별 차등 지원.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, 'undergrad_transfer', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('배재가족자녀장학금', '배재대학교', '배재대학교 출신 부모(동문)의 자녀 대상.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('한가족장학금', '배재대학교', '2촌 이내 친족이 동시에 배재대에 재적 중인 학생 대상. 등록금 30% 이내 지원.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('새터민장학금(배재대)', '배재대학교', '북한이탈주민 대상. 직전학기 평점평균 1.91 이상. 등록금 전액 지원.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, 1.91, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('교직원복지장학금', '배재대학교', '배재학당 소속 교직원의 자녀 대상. 등록금 전액 지원.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('배재사랑장학금', '배재대학교', '장애학생 또는 다문화가정 학생 대상. 등록금 30% 지원.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('성적전액장학금', '배재대학교', '직전학기 평점평균 3.5 이상 재학생 대상. 수업료 전액 지원.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, 3.5, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, 'undergrad_enrolled', NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('영어성적우수장학금', '배재대학교', 'TOEIC 900점 이상(영어 전공자는 950점 이상) 재학생 대상. 1학기 수업료 전액 지원. 시험 종류·점수 조건이라 현재 시스템 필드로는 매칭 불가.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'academic_merit'),
('희망복지장학금', '배재대학교', '기초생활수급자·차상위계층·한부모가족 학생 대상. 등록금 50% 이내 지원.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('솔선장학금', '배재대학교', '저소득층 학생 대상(직전학기 평점평균 1.91 이상).', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, 1.91, 'semester', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'welfare_living'),
('국가유공장학금', '배재대학교', '국가보훈대상자 대상. 등록금 전액 지원.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('교역직계장학금', '배재대학교', '기독교대한감리회 교역자 자녀 대상(배재대는 감리교 재단 학교).', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('교육직계장학금', '배재대학교', '초·중·고등학교 교사의 자녀 대상.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'special_target'),
('격려장학금', '배재대학교', '학생자치기구 임원·ROTC·체육부 등 소속 학생 중 추천을 받은 자 대상. 수업료 일부 지원.', NULL, 'https://www.pcu.ac.kr/kor/contents/33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '매 학기 초 공지 (배재대 홈페이지 확인)', '배재대학교', NULL, NULL, NULL, NULL, NULL, 'school_internal', 'activity_merit');

-- 배치 2: 장학공지 게시판(외부재단) 중 신규 확인분 (2건, id 173~174, 대학 무관 지역기반이라 eligible_university NULL)
INSERT INTO scholarship (name, provider, description, amount, application_url, min_age, max_age, required_gender, eligible_region, required_military_status, max_income_bracket, min_gpa, min_gpa_basis, requires_disability, foreigner_eligibility, grade_level, major, affiliated_institution, min_credits, admission_score_condition, headcount, application_period, eligible_university, eligible_college, required_enrollment_status, min_grade, max_grade, required_degree_level, category_l1, category_l2) VALUES
('서울인재대학장학금', '서울미래인재재단', '서울 소재 대학 재학 또는 서울시민의 자녀로 비서울 소재 대학 재학 중인 2학년 이상 학생 대상. 기초생활수급자/차상위/학자금지원 4구간 이하, 전체학기 평점 백분위 90점 이상(4.5만점 GPA 아님, 백분위 성적 기준이라 min_gpa로 환산 불가). 연 200만원 1회 지급.', 2000000, 'https://www.seoulfuture.or.kr', NULL, NULL, NULL, '서울', NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '전체학기 평점 백분위 90점 이상(백분위 기준, GPA 아님)', NULL, '2026.8.3~8.10', NULL, NULL, NULL, 2, NULL, NULL, 'school_external', 'local_gov'),
('대학(원)생 학자금대출 이자지원(울산)', '울산광역시', '주민등록상 주소지가 울산인 대학(원) 재학생·휴학생 대상. 2017년 이후 한국장학재단 학자금대출 이자(2026년 1~6월분) 전액 지원.', NULL, 'https://www.ulsan.go.kr', NULL, NULL, NULL, '울산', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026.7.31~8.30', NULL, NULL, NULL, NULL, NULL, NULL, 'support_fund', 'youth_living_support');
