-- id=38~71 CNU 재학생/법인 장학금 표 원문(plus.cnu.ac.kr, 이미 다운받은 표 텍스트로 재대조) 반영
-- 주의: 복수학위(51)와 학·석사연계과정(학부)(61)은 표 제목이 "직전학기평균평점"이지만 비고란에
-- "전체 학기(누적) 성적 기준"이라는 예외가 명시돼 있어서 min_gpa_basis를 cumulative로 넣음.

UPDATE scholarship SET amount_detail='등록금 전액', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='성적우수자', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=38;
UPDATE scholarship SET amount_detail='등록금 일부(A급)', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='성적우수자(성적우수와 동일 기준)', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=39;
UPDATE scholarship SET amount_detail='학업장려금 일부', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='성적우수자(별도기준, 구체적 커트라인은 원문에 없음)', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=41;
UPDATE scholarship SET amount_detail='등록금 일부(C급)', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='성적우수자', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=42;
UPDATE scholarship SET amount_detail='등록금 전액', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='성적우수자, 경제·사회적 취약계층, 봉사활동으로 본교에 기여한 자', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=43;
UPDATE scholarship SET amount_detail='등록금 일부', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='성적우수자, 경제·사회적 취약계층, 봉사활동으로 본교에 기여한 자', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=44;
UPDATE scholarship SET amount_detail='등록금 일부', application_method='자동선발 — 별도 신청 절차 없이 국가장학금 신청 결과 기준으로 선발', headcount='적격자', description='이연자(등록유효복학자), 수업연한초과자는 제외됨' WHERE id=45;
UPDATE scholarship SET amount_detail='등록금 또는 생활비 일부', application_method='직접 신청 필요 — 학생과에 서류 제출', admission_score_condition='경제적 사정이 곤란한 자', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=46;
UPDATE scholarship SET amount_detail='등록금 전액', application_method='직접 신청 필요 — 학생과에 서류 제출', headcount='총장이 정하는 인원', min_gpa_basis='semester', description='장애의 정도가 심한 장애인 대상(장애 정도 구분은 우리 시스템에서 판단 못함 — 장애 등록 여부만 확인)' WHERE id=47;
UPDATE scholarship SET amount_detail='등록금 일부(A급)', application_method='직접 신청 필요 — 학생과에 서류 제출', headcount='총장이 정하는 인원', min_gpa_basis='semester', description='장애의 정도가 심하지 않은 장애인 대상(장애 정도 구분은 우리 시스템에서 판단 못함 — 장애 등록 여부만 확인)' WHERE id=48;
UPDATE scholarship SET amount_detail='등록금 전액', application_method='자동선발 — 별도 신청 절차 없이 체육진흥원 추천 기준으로 선발', admission_score_condition='체육진흥원 추천자', headcount='적격자', min_gpa_basis='semester', description=NULL WHERE id=49;
UPDATE scholarship SET amount_detail='등록금 전액', application_method='정부초청외국인장학생(GKS) 프로그램 결과 연동 — 별도 신청 불필요', admission_score_condition='정부초청 외국인 장학생', headcount='적격자', min_gpa_basis='semester', description=NULL WHERE id=50;
UPDATE scholarship SET amount_detail='등록금 전액(4개학기)', application_method='국제교류본부장 추천 필요', admission_score_condition='국제교류본부장 추천자', headcount='적격자', min_gpa_basis='cumulative', description=NULL WHERE id=51;
UPDATE scholarship SET amount_detail='등록금 일부(A급)', application_method='점수 제출 필요 — 학생과에 TOEIC/TOEFL 성적표 제출(자격취득일부터 1년 이내 성적만 인정, 재학중 1회만 수혜 가능)', admission_score_condition='TOEIC 900점 이상 또는 TOEFL iBT 102점 이상 (ETS 주관 시험)', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=52;
UPDATE scholarship SET amount_detail='등록금 전액(정규학기)', application_method='자동선발 — 국제교류본부 추천 기준으로 선발', admission_score_condition='6.25 유엔참전용사 후손(직계비속)임이 확인된 외국인 유학생(국제교류본부 추천자)', headcount='적격자', min_gpa_basis='semester', description=NULL WHERE id=53;
UPDATE scholarship SET amount_detail='등록금 일부(B급)', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='외국인 유학생(국적이 대한민국인 경우 제외)', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=54;
UPDATE scholarship SET amount_detail='등록금 일부', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='외국인 유학생', min_gpa_basis='semester', description=NULL WHERE id=55;
UPDATE scholarship SET amount_detail='등록금 일부', application_method='자동선발 — 해외 교류대학 복수학위 참가 여부 기준으로 선발', admission_score_condition='해외 교류대학 복수학위 참가자', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=56;
UPDATE scholarship SET amount_detail='등록금 전액(정규학기). 본인은 성적·지급학기 제한 없음.', application_method='직접 신청 필요 — 학생과에 서류 제출', admission_score_condition='국가유공자 본인 및 자녀', headcount='적격자', min_gpa_basis='semester', description=NULL WHERE id=57;
UPDATE scholarship SET amount_detail='등록금 전액(정규학기)', application_method='직접 신청 필요 — 학생과에 서류 제출', admission_score_condition='북한이탈주민', headcount='적격자', min_gpa_basis='semester', description=NULL WHERE id=58;
UPDATE scholarship SET amount_detail='등록금 전액 또는 일부', application_method='학생 신청 대상 아님 — 학생자치기구 임원 등 특정 직위자를 학교가 직권으로 선발', admission_score_condition='학생자치기구 임원 등', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=59;
UPDATE scholarship SET amount_detail='등록금 일부(C급, 3개학기)', application_method='자동선발 — 군 위탁교육 신분 기준으로 선발', admission_score_condition='대학원 정원 외 군(육·해·공) 위탁교육생', headcount='적격자', min_gpa_basis='semester', description=NULL WHERE id=60;
UPDATE scholarship SET amount_detail='학업장려금(학부과정 전체학기 3회 이내, 매회 150만원)', application_method='자동선발 — 학·석사연계과정 유지 여부 기준으로 선발', admission_score_condition='학·석사연계과정 계속 유지자로 학부과정 매학기 이수 이후 지급(이수학기 포함 전체 성적 평균평점 3.75 이상)', headcount='총장이 정하는 인원', min_gpa_basis='cumulative', description=NULL WHERE id=61;
UPDATE scholarship SET amount_detail='학업장려금(월 70만원, 최대 5개월)', application_method='자동선발 — BK21 교육연구단(팀) 참여자 대상', admission_score_condition='학·석사연계과정(학부) 최종학기 재학생으로 BK21 교육연구단(팀)의 교육과정 및 연구활동에 참여하는 자', headcount='적격자', min_gpa_basis='cumulative', description='학·석사연계과정(학부) 학업장려금과 동일학기 중복 수혜 불가' WHERE id=62;
UPDATE scholarship SET amount_detail='해외연수비(연도별 지급기준액 별도 책정)', application_method='공모 지원 필요 — 학생군사교육단 해외프로그램 공모 참여', admission_score_condition='학생군사교육단 해외프로그램 공모에 선발된 자', headcount='적격자', min_gpa_basis='semester', description=NULL WHERE id=63;
UPDATE scholarship SET amount_detail='학업장려금', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='성적우수자(별도기준, 구체적 커트라인은 원문에 없음)', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=64;
UPDATE scholarship SET amount_detail='학업장려금 일부', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='성적우수자(별도기준, 구체적 커트라인은 원문에 없음)', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=65;
UPDATE scholarship SET amount_detail='등록금 전액 또는 일부', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='학·석사연계과정(석사) 전일제 재학생', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=66;
UPDATE scholarship SET amount_detail='등록금 전액 또는 일부', application_method='자동선발 — 별도 신청 절차 없이 선발', admission_score_condition='석·박사통합과정 전일제 재학생', headcount='총장이 정하는 인원', min_gpa_basis='semester', description=NULL WHERE id=67;
UPDATE scholarship SET amount_detail='연구장려금', application_method='일반대학원장 추천 또는 실적 제출 필요', admission_score_condition='논문게재, 학술대회 참가 등 일반대학원장이 정한 실적을 충족한 자(구체적 기준은 원문에 없음)', headcount='총장이 정하는 인원', description=NULL WHERE id=68;
UPDATE scholarship SET amount_detail='연구장려금', application_method='일반대학원장 추천 필요', admission_score_condition='연구지원이 필요한 전일제 대학원생으로 일반대학원장이 추천한 자', headcount='총장이 정하는 인원', description=NULL WHERE id=69;
UPDATE scholarship SET amount_detail='학업장려금 100만원', application_method='자동선발 — 별도 신청 절차 없이 수능 성적 기준으로 선발', admission_score_condition='수능 성적 우수자', min_gpa_basis='semester', description=NULL WHERE id=70;
UPDATE scholarship SET amount_detail='학업장려금 일부 (정확한 금액 원문에 명시 안 됨)', application_method='자동선발로 추정 — 원문에 구체적 신청방법 명시 안 됨', required_enrollment_status='undergrad_enrolled', description=NULL WHERE id=71;
